### ISSUE TITLE
Add tree like dropdown

### ISSUE THREAD

**Issue by nimesha95** [handsontable/react-handsontable#103]
Hi, i'm looking for the exact same features described from below link. Is it possible to do this? 
Thanks for this amazing library! :) 
[https://github.com/handsontable/handsontable/issues/1924](https://github.com/handsontable/handsontable/issues/1924)

**Comment by AMBudnik** [comment]
Hi @nimesha95 

have you tried our nestedRows feature https://docs.handsontable.com/pro/5.0.2/demo-nested-rows.html ?

**Comment by nimesha95** [comment]
Thanks, it works, i have a follow up question about this feature. is it possible to customize the size of the "+" , "-" icons?

**Comment by wojciechczerniak** [comment]
It's pure CSS. Target the `ht_nestingButton ht_nestingCollapse` classes and style them however you like it.
