### ISSUE TITLE
Making the wrapper compatible with CommonJS

### ISSUE THREAD

**Issue by guillaumep** [handsontable/react-handsontable#106]
I've got a TypeScript project configured to use commonjs module imports and I can't use the React wrapper, as I get this error:

```
ERROR in [at-loader] ./node_modules/@handsontable/react/index.d.ts:5:8 
    TS1192: Module '"/home/user/code/git/myproject/node_modules/@types/react/index"' has no default export.

ERROR in [at-loader] ./node_modules/@handsontable/react/index.d.ts:6:8 
    TS1192: Module '"/home/user/code/git/myproject/node_modules/handsontable/handsontable"' has no default export.
```

In `src/common/index.tsx` and in the code examples you import React in the following way:

`import React from 'react';`

Whereas in commonjs we use:

`import * as React from 'react';`

react-handsontable is configured the following way in `tsconfig.json`:

```
    "module": "esnext",
    "moduleResolution": "node",
```

Could you explain why exnext is used? And is there a way to have us commonjs users be able to use the TypeScript binding?

As a side note, a typical commonjs configuration in `tsconfig.json` would be:

```
    "module": "commonjs",
```

(no moduleResolution line)

### Your environment
* React wrapper version: 1.1.0
* Handsontable version: 5.0.2
* Operating System: Linux

**Comment by guillaumep** [comment]
For those having the same issue, I have used [patch-package](https://github.com/ds300/patch-package/) to apply this patch to the `@handonstable/react package`:

```
--- a/node_modules/@handsontable/react/index.d.ts
+++ b/node_modules/@handsontable/react/index.d.ts
@@ -2,8 +2,8 @@
 //   ../../react
 //   ../../handsontable
 
-import React from 'react';
-import Handsontable from 'handsontable';
+import * as React from 'react';
+import * as Handsontable from 'handsontable';
```

**Comment by wojciechczerniak** [comment]
ES6 module is an ECMA Script standard. If you still use CommonJS system then Typescript 2.7 have introduced [1] `allowSyntheticDefaultImports` and `esModuleInterop` flags for compatibility with ES6 modules. And they "highly recommend applying it both to new and existing projects". All the details are in Typescript 2.7 Release Notes [1]. I've got a project configured with `"module": "commonjs"` like you do and it works perfectly. 

We also have a CommonJS build in `/commonjs` directory, ES6 build in `/es` directory and UMD build in `/dist` directory. Tools like Webpack, Babel, etc. will choose the right build file by reading `package.json` keys.

[1] [https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-form-commonjs-modules-with---esmoduleinterop](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-form-commonjs-modules-with---esmoduleinterop)

**Comment by guillaumep** [comment]
@wojciechczerniak Thanks for the detailed answer. I will try your recommendations as soon as possible but I have no doubt it will address my issues. Closing the ticket.
