### ISSUE TITLE
Get the row data in nested view

### ISSUE THREAD

**Issue by nimesha95** [handsontable/react-handsontable#107]
Hi, 
How can i access the data row (or  tree) when given a row index of a updated cell.
Currently i'm accessing the row index of updated cell by using 'afterChange' function. Is there a way to access the data of the whole tree (or atleast updated row)
(I cannot directly access the props data by row id because i'm using nested view)

Edit: is there a way to use "getDataAtRow" function to do above task?

**Comment by AMBudnik** [comment]
Hi @nimesha95 

sure, you can and it is the best way.

Here is a working demo https://jsfiddle.net/handsoncode/d1x42rvf/
