### ISSUE TITLE
What is correct config for expose-loader in webpack2?

### ISSUE THREAD

**Issue by w-** [handsontable/react-handsontable#11]
I originally craeted issue #10 
after playing around it looks like the way we configure expose-loader in webpack config is not having desired effect.

the error i get is now

> Uncaught Error: Cannot find module 'numbro'
>     at newRequire (handsontable.js:53)
>     at handsontable.js:60
>     at Object.23.cellTypes (handsontable.js:4479)
>     at newRequire (handsontable.js:58)
>     at outer (handsontable.js:66)
>     at handsontable.js:71
>     at webpackJsonp../node_modules/handsontable/dist/handsontable.js.previousRequire (handsontable.js:27)
>     at Object.<anonymous> (handsontable.js:27)
>     at Object../node_modules/handsontable/dist/handsontable.js (stupidApp.1793dcd….js:25771)
>     at __webpack_require__ (bootstrap 1793dcd…:691)

I've looked at the docs and also at issue #3 

relevant part of webpack config looks like

>      {
>         test: require.resolve('handsontable'),
>         loader: 'expose-loader?Handsontable'
>       },
>       {
>         test: require.resolve('numbro'),
>         loader: 'expose-loader?numbro',
>         //options: {'numbro': null}
>       },
>       {
>         test: require.resolve('moment'),
>         loader: 'expose-loader?moment'
>       },
>       {
>         test: require.resolve('pikaday'),
>         loader: 'expose-loader?Pikaday'
>       },
>       {
>         test: require.resolve('zeroclipboard'),
>         loader: 'expose-loader?ZeroClipboard'
>       },

inside the relevant react component I import as outlined by the docs:

```js
import moment from 'moment';
import numbro from 'numbro';
import pikaday from 'pikaday';
import Zeroclipboard from 'zeroclipboard';
import Handsontable from 'handsontable';
import HotTable from 'react-handsontable';
import 'handsontable/dist/handsontable.full.css';
```

but if i do window.numbro I can see that it is undefined. 
Why isn't the expose loader doing it's job?

**Comment by flatanimals** [comment]
See: https://github.com/webpack-contrib/expose-loader#usage

The following config should do it:

```js

{
  module: {
    rules: [
      {
        test: require.resolve('numbro'),
        use: [{
          loader: 'expose-loader',
          options: 'numbro'
        }]
      },
      {
        test: require.resolve('moment'),
        use: [{
          loader: 'expose-loader',
          options: 'moment'
        }]
      },
      {
        test: require.resolve('pikaday'),
        use: [{
          loader: 'expose-loader',
          options: 'Pikaday'
        }]
      },
      {
        test: require.resolve('zeroclipboard'),
        use: [{
          loader: 'expose-loader',
          options: 'ZeroClipboard'
        }]
      },
    ]
  }
}

```

**Comment by w-** [comment]
thx.
thought i was crazy for not noticing those webpack2 docs before but turns out they were just added.
https://github.com/webpack-contrib/expose-loader/commit/e6125cf526279558f0e7d605545919a27910308c

will try and report back.

**Comment by w-** [comment]
unfortunately that updated config still does not work.

module.rules:
```js
{
        test: require.resolve('numbro'),
        use: [{
          loader: 'expose-loader',
          options: 'numbro', 
        }],
      },
      {
        test: require.resolve('moment'),
        use: [{
          loader: 'expose-loader',
          options: 'moment',
        }],
      },
      {
        test: require.resolve('pikaday'),
        use: [{
          loader: 'expose-loader',
          options: 'Pikaday',
        }],
      },
      {
        test: require.resolve('zeroclipboard'),
        use: [{
          loader: 'expose-loader',
          options: 'ZeroClipboard',
        }],
      },  
```

error:

> Uncaught Error: Cannot find module 'numbro'
>     at newRequire (handsontable.js:53)
>     at eval (handsontable.js:60)
>     at Object.23.cellTypes (handsontable.js:4479)
>     at newRequire (handsontable.js:58)
>     at outer (handsontable.js:66)
>     at eval (handsontable.js:71)
>     at previousRequire (handsontable.js:27)
>     at Object.eval (handsontable.js:27)
>     at eval (handsontable.js:25474)
>     at Object../node_modules/handsontable/dist/handsontable.js (....

**Comment by robarchibald** [comment]
The suggestion by @flatanimals worked for me on webpack 2.6.1 with the vue-handsontable-official v0.2.5 component and handsontable 0.32.0. I know it's not react, but it's webpack 2 so I figure it's the same issue since I had the same error previously. I'll submit an update to the wiki docs for vue-handsontable-official. Thanks!

**Comment by anevaude** [comment]
Hello. I just wanted to chime in and say the solution above worked for me. To any other developers who are trying to install react-handsontable and have been seeing these errors:

cannot find module 'numbro'
cannot find module 'pikaday'

Adding expose-loader to my webpack.config.js file made it so HandsOnTable now appears.

**Comment by AMBudnik** [comment]
Thank you for sharing the hits. We will be updating the wrapper later this year so thank you all for feedback.
