### ISSUE TITLE
Zoom Browser window，table does not display normaly?

### ISSUE THREAD

**Issue by allan2coder** [handsontable/react-handsontable#118]
### Description
Zoom Browser window，table does not display normaly?

### Zoom Browser window
![image](https://user-images.githubusercontent.com/14307551/48828872-d4ca0500-edab-11e8-9dd6-e3c4873ebd90.png)

### Your environment
mac and windows system browser

**Comment by AMBudnik** [comment]
Hey @allan2coder 

Can you send me over a demo where this issue can be replicable?

I wasn't able to replicate it with this demo https://handsontable.com/docs/6.2.0/demo-hiding-columns.html

**Comment by wojciechczerniak** [comment]
Closing this as we can't replicate the issue.
