### ISSUE TITLE
TypeScript types are incorrect

### ISSUE THREAD

**Issue by tswistak** [handsontable/react-handsontable#123]
### Description
It appears that typings aren't working. I've a project with latest versions of React and Handsontable and during Typescript type check I get an error:

> JSX element type 'HotTable' is not a constructor function for JSX elements. Property 'context' is missing in type 'HotTable'. [2605]

During compilation the error is more detailed:

> index.tsx:20:18 - error TS2322: Type '{ data: ReactText[][]; colHeaders: boolean; rowHeaders: boolean; width: number; height: number; stretchH: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<HotTable> & HotTableProps'.
  Property 'colHeaders' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<HotTable> & HotTableProps'.

### Demo
I've created a repo where you can find a sample project with this issue: https://github.com/tswistak/react-handsontable-typings-issue . After reinstalling packages, run tsc and the error should occur.

I've found a way to bypass the issue. In this repo I've uploaded there is also a typings directory, where you can find alternative typings for the library. After uncommenting it, project compiles. If these typings are OK, I can create a pull request to the repo.

### Your environment
* React wrapper version: 2.1.0
* Handsontable version: 6.2.0
* Browser Name and version: not relevant
* Operating System: Windows 10 Pro

**Comment by wojciechczerniak** [comment]
We've rewritten the wrapper to Typescript in v1.1.0 so the typings are auto generated. What you're missing is the `"esModuleInterop": true` config in your `tsconfig.json`. Thanks for your effort and PR

Ref #116 #106
