### ISSUE TITLE
Error creating HotTable component when using TypeScript and WebPack

### ISSUE THREAD

**Issue by panesofglass** [handsontable/react-handsontable#13]
I receive the following error trying to mount a web app built with TypeScript 2.2.2 and WebPack 2.3.2:

> Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `Demo`.

![image](https://cloud.githubusercontent.com/assets/8803/24471045/7c23519a-1486-11e7-85f8-bdb4feb73ece.png)

Repro repo: https://github.com/panesofglass/hottest

**Comment by muffadalis** [comment]
@panesofglass  I had similar issue your sample repo helped my a lot. Thanks

**Comment by wojciechczerniak** [comment]
Wrapper was rewritten in Typescript as a part of issue #14 and has a definition file now. We have tested it with Typescript and Webpack so this problem should be solved now.
