### ISSUE TITLE
Add HotColumn element

### ISSUE THREAD

**Issue by jansiegel** [handsontable/react-handsontable#130]
⚠️ Work in progress

### Description
We need a component to declare columns inside `HotTable` element.

- [ ] Add `<hot-column>` component
  - [ ]  Docs: Add an example with declared `<hot-column>`
  - [ ]  Docs: Add an example with `<hot-column>` and for loop

- [ ] Support React components as `hot-renderer` or `hot-editor` #21
   - [ ] Docs: Add an example with `hot-renderer`
   - [ ] Docs: Add an example with `hot-editor`

### Basic use case

```jsx
import {HotTable, HotColumn} from '@handsotnable/react';

class App extends React.Component {
  render() {
    return (
      <HotTable settings={this.hotSettings}>
        <HotColumn title={'fist column'}/>
        <HotColumn title="second column">
      </HotTable>
    );
  }
}
```

### Map
```jsx
import {HotTable, HotColumn} from '@handsotnable/react';

class App extends React.Component {
  constructor() {
     this.columns = [ ... ];
  }

  render() {
    return (
      <HotTable settings={this.hotSettings}>
        {this.columns.map((column) => (<HotColumn settings={column}/>))}
      </HotTable>
    );
  }
}
```

### Custom renderer and editor
```jsx
import {HotTable, HotColumn} from '@handsotnable/react';
import {CustomEditor} from './CustomEditor';
import {CustomRenderer} from './CustomRenderer';

class App extends React.Component {
  constructor() {
     this.columns = [ ... ];
  }

  render() {
    return (
      <HotTable settings={this.hotSettings}>
        <CustomEditor hot-editor />
        <CustomRenderer hot-renderer/>
      </HotTable>
    );
  }
}
```

### Additional `wrap` helper so we can use react renderers globally

Requires `rendererCache` access. Should we attach wrapper instance to HoT? https://github.com/handsontable/vue-handsontable-official/issues/129
```jsx
import { wrapComponent } from '@handsontable/react`;
​
Handsontable.renderers.registerRenderer('LinkRenderer', wrapComponent(LinkRenderer));
```

**Comment by AMBudnik** [comment]
inform `Zen 22973`

**Comment by AddoSolutions** [comment]
So, how exactly does one use this? I see a bunch of code comments, but isn't clear in the docs, and `wrapComponent` isn't exported by `@handsontable/react`, so I must be missing something here

**Comment by wojciechczerniak** [comment]
Hi @AddoSolutions, have you seen [Using the HotColumn component](https://handsontable.com/docs/8.0.0/frameworks-wrapper-for-react-hot-column.html) in the docs?

**Comment by AddoSolutions** [comment]
Nope, but that looks like the ticket :)

Thank you!
