### ISSUE TITLE
Handsontable 7.0.0+ using React 

### ISSUE THREAD

**Issue by pnowak** [handsontable/react-handsontable#133]
### Description
After update `handsontable` version from `6.2.2` to `7.0.0` (or higher) and `@handsontable/react`: `^2.0.0`, to` ^3.0.0`. And then run `npm install` and then `npm run start` we get the error:
```Error: Can't resolve 'core-js/modules/web.dom-collections.iterator' in '/Users/kim/Documents/Apps/WebApps/eno-a3-django/node_modules/handsontable/es/plugins/manualColumnResize'```

### Demo

[handsontable-react.zip](https://github.com/handsontable/react-handsontable/files/3261111/handsontable-react.zip)

https://github.com/handsontable/support/issues/117

### Your environment
* React wrapper version:
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
@pnowak I guess that we should close this topic, as like mentioned by @wojciechczerniak 

> in this example the logic of finding the modules has been overwritten, so Handsontable looks for the older 'core-js' version even when it has a newer one installed.
