### ISSUE TITLE
hide / filter all the columns that contain a specific string in the header

### ISSUE THREAD

**Issue by OmarKhattab** [handsontable/react-handsontable#135]
### Description
My data structure contains values that should not be viewed or edited on the client and are required for later writes to the database. I want to learn how to hide / filter all the columns with a specific string in the header such as "ID" using the hands on table react wrapper.

Stackblitz below shows an isolated use-case.

### Demo

https://stackblitz.com/edit/hands-on-table-react-how-to-hide-columns-with-id-as-key

### Your environment
* React wrapper version: 3.0.0
* Handsontable version: 7.1.0
* Browser Name and version: Google Chrome
* Operating System: Mac OS

**Comment by AMBudnik** [comment]
Hey @OmarKhattab 
It looks like those are some particular columns. So if you know their indexes you can gather them and pass as an array to the [hiddenColumns option](https://handsontable.com/docs/7.1.0/demo-hiding-columns.html).

**Comment by OmarKhattab** [comment]
@AMBudnik thanks for the solution. Is there any other way to hide columns? Maybe by the heading key that would be very useful.

**Comment by wojciechczerniak** [comment]
@OmarKhattab Use `columns` setting to define which columns should be displayed and map data objects to them: https://handsontable.com/docs/7.1.0/tutorial-data-sources.html#page-nested
