### ISSUE TITLE
After column sorting, I need it to write changes to react state

### ISSUE THREAD

**Issue by alexturbulent** [handsontable/react-handsontable#137]
### Description

Hey. I need to set changes into react state after column sorting (asc, des). As my understanding handsontable uses visual view to sort, columnMove and etc. It doesn't write sorting changes into state.

### Your environment
* React wrapper version: 3.0.0
* Handsontable version: 6.2.2
* Browser Name and version: Chrome Version 76.0.3809.87 (Official Build) (64-bit)
* Operating System: Windows 10 (64-bit)

**Comment by wojciechczerniak** [comment]
Hi. You're looking for `getData()` method. It will return data after the modifications.

**Comment by alexturbulent** [comment]
Thanks. It works but I have used array of objects, is there a way to get data as it is, getData() returns array of arrays.

**Comment by wojciechczerniak** [comment]
No, I don't see any method that could help here. You could map all indexes with `toPhysicalRow()` method and order rows on your own. But columns are props, and not always all of them are in use. This is left up to the developer to decide.
