### ISSUE TITLE
How to unmount component when the row is invisible?

### ISSUE THREAD

**Issue by jacktang** [handsontable/react-handsontable#138]
First of all, thanks for the great component!

I want to extend some features by React components by CellRenderer like below:
```javascript
if (col === 0) {
      const dom = document.createElement('div');
      const component = (
        <Provider store={store}>
          <Balloon align="r"
            trigger={<span>{value}</span>}
            closable={false}
            afterClose={() => {
           
          }}
          >
            <div style={{ width: '800px', height: '500px' }}>
              <OtherComponent .... />
            </div>
          </Balloon>
        </Provider>
      );
      ReactDOM.render(component, dom);
      td.innerHTML = '';
      td.appendChild(dom);
    }
```
It is well rendered when row is visible, and if the row becomes invisible, the DOM element is removed, but the react component is not removed and make memory leaks. 

My question is any event or callbacks I should listen on so that I can `unmountComponentAtNode` properly?

**Comment by wojciechczerniak** [comment]
Thanks!

Unfortunately there is none. Our approach is to use LRUMap

https://github.com/handsontable/react-handsontable/blob/bec46ad875f0f20729acba21e1b7009e1d7700b2/src/hotTable.tsx#L97

The map has an event when an item is removed from cache. I don't see it implemented for React, yet. It's a work in progress. It will basically work the same as in our vue wrapper: 

https://github.com/handsontable/vue-handsontable-official/blob/6621371767ddf74b2224b54c85559551ed0595f3/src/HotTable.vue#L42-L47

**Comment by jacktang** [comment]
@wojciechczerniak Thanks for the idea! I will have a try.

**Comment by wojciechczerniak** [comment]
You can also track #130, components inside cell will be supported by us very soon.
