### ISSUE TITLE
TypeError: Cannot read property 'renderer' of undefined

### ISSUE THREAD

**Issue by sbzmpa** [handsontable/react-handsontable#141]
https://github.com/handsontable/react-handsontable/blob/78848f87cf0253273a51ba54560550fbeeb3fc1c/src/hotTable.tsx#L375

columns in HotTable settings are defined as function:

columns: index => {
    return {
        renderer: hotTable.textRender
    }
}

**Comment by AMBudnik** [comment]
Hi @sbzmpa 

Please create a demo or/and bug scenario.

**Comment by sbzmpa** [comment]
How exactly can I do that?

**Comment by AMBudnik** [comment]
Here https://jsfiddle.net/y62jar1c/ is a React for Handsontable example. Please fill the settings that you use. You do not need to paste everything - just the settings that are needed to replicate the issue. 

Once you get everything done you click `fork` button

![image](https://user-images.githubusercontent.com/10757813/67859808-c4beb780-fb1c-11e9-9b30-63e576a88a0a.png)

in the result you get a new dedicated link that you can share.

**Comment by sbzmpa** [comment]
We have several deployments of application that uses Handsontable. Only one of them gives that error:

Handsontable.js:44 TypeError: Cannot read property 'renderer' of undefined
    at t.value (react-handsontable.js:950)
    at t.value (react-handsontable.js:1056)
    at react-dom.production.min.js:6321
    at t.unstable_runWithPriority (scheduler.production.min.js:266)
    at qo (react-dom.production.min.js:2794)
    at xl (react-dom.production.min.js:6105)
    at gl (react-dom.production.min.js:5408)
    at react-dom.production.min.js:2829
    at t.unstable_runWithPriority (scheduler.production.min.js:266)
    at qo (react-dom.production.min.js:2794)

**Comment by AMBudnik** [comment]
That should make the case easier. What do you use in that single table that differs from the rest (working examples)? A renderer is used along the way in all processes and by all plugins so I'd need to know more about the bug scenario.

**Comment by sbzmpa** [comment]
All deployments have the same source code and we haven't localized the problem yet. The hypothesis is - usage of different versions of Handsontable and/or react-handsontable.
I'll get back with details if I find something or if I would be able to reproduce the bug in jsfiddle.

**Comment by sbzmpa** [comment]
How can I use the latest versions of Handsontable and/or react-handsontable in the fiddle you mentioned?
These
<script src="https://cdn.jsdelivr.net/npm/handsontable-pro@7.0.3/dist/handsontable.full.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@handsontable-pro/react@3.1.0/dist/react-handsontable.min.js"></script>
don't work.

The displayAutoSizeWarning function was created in 3.1.0 release, about 2 days ago. That's when the bugs began to appear in our deployment.

**Comment by sbzmpa** [comment]
Here's fiddle with this error
https://jsfiddle.net/4tg9kcys/

**Comment by AMBudnik** [comment]
Thank you for sharing the demo @sbzmpa 

Sorry that I did not answer immediately but we've checked the code and moved with fixes in https://github.com/handsontable/react-handsontable/pull/142 so it shouldn't take us long to published the changes

**Comment by sbzmpa** [comment]
No probs, Aleksandra! Thank you for quick response on the issue .

**Comment by AMBudnik** [comment]
Hey @sbzmpa 

I'm happy to announce that we've just updated the wrapper and fixed this issue. Thank you very much for sharing. We make this library better together :)

**Comment by sbzmpa** [comment]
Thank you, guys!
