### ISSUE TITLE
use columns renderer has bug 

### ISSUE THREAD

**Issue by yangQingYu123** [handsontable/react-handsontable#143]
### Description
Warning: render(...): It looks like the React-rendered content of this container was removed without using React. This is not supported and will cause errors. Instead, call ReactDOM.unmountComponentAtNode to empty a container.

### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/c6rgz08x/

### Your environment
* React wrapper version:
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by jansiegel** [comment]
@yangQingYu123 Could you be more specific about when this warning appears? I can't see it in the jsfiddle you linked and you didn't provide any steps for reproduction.
