### ISSUE TITLE
3.1.0 Erases most Typescript definitions

### ISSUE THREAD

**Issue by dboskovic** [handsontable/react-handsontable#144]
### Description
As of 3.1.0, almost all valuable TS definitions are gone. I believe that this function just needs some generic type variables and it'd resolve the issue:

https://github.com/handsontable/react-handsontable/blob/3331959cd0ddc887c867f8839cb342f8313ab7f2/src/helpers.tsx#L153-L166

See generated TS definitions:
https://unpkg.com/@handsontable/react@3.0.0/hotTable.d.ts
https://unpkg.com/@handsontable/react@3.1.0/hotTable.d.ts

**Comment by jansiegel** [comment]
@dboskovic You're right, it definitely needs fixing. Thanks for reporting!

**Comment by PaulPCIO** [comment]
+1 hope this will be fixed soon, busy setting up a presentation for my team to compare handsontable and ag-grid, without the typescript support handsontable will never get accepted for our production.

**Comment by AMBudnik** [comment]
Hey @PaulPCIO we're already doing the Code Review.
It shouldn't take us long to push a fix.

**Comment by jansiegel** [comment]
@PaulPCIO, @dboskovic `@handsontable/react@3.1.2` was just released, so this issue should no longer be a problem.
