### ISSUE TITLE
Npm audit security warning on master and on develop

### ISSUE THREAD

**Issue by aninde** [handsontable/react-handsontable#148]
### Description
There's an npm audit security warning on the current `master` and `develop` branch that needs to be addressed.

![Screenshot 2019-12-11 at 15 17 24](https://user-images.githubusercontent.com/30186818/70628933-5f84d880-1c29-11ea-947e-ca0c99269f5f.png)

**Comment by jansiegel** [comment]
Fixed with `3.1.2`.
