### ISSUE TITLE
How to custom contextMenu and handle click on context menu item events

### ISSUE THREAD

**Issue by CongLeVN** [handsontable/react-handsontable#15]
Please guild me how to custom context menu as handsontable js library. Thanks.

**Comment by AMBudnik** [comment]
Hi @CongLeVN 

we do not have a lot of React demos yet but I have a vanilla demo at http://jsfiddle.net/vyjm0Lcc/
I hope that I will help.
Surely a context menu example is one of those that we can add later to the wrapper's demo list.

**Comment by plinyar** [comment]
@AMBudnik is the demo corrupted?

**Comment by AMBudnik** [comment]
It looks like I've sent the wrong example. Here is a custom context menu http://jsfiddle.net/rdu2bq2z/

**Comment by wojciechczerniak** [comment]
Documentation was updated in #104
