### ISSUE TITLE
Bump handsontable version to 7.3.0

### ISSUE THREAD

**Issue by joaopluigi** [handsontable/react-handsontable#153]
### Description
Update handsontable package to [version 7.3.0](https://github.com/handsontable/handsontable/releases/tag/7.3.0) in order to get the latest fixes

**Comment by AMBudnik** [comment]
Hey @joaopluigi 

this

``` js
"peerDependencies": {
    "handsontable": ">=7.2.2"
  },
```

tells us that we can use `7.2.2` and `7.3.0`.
src https://devhints.io/semver

**Comment by joaopluigi** [comment]
@AMBudnik, thanks!
