### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by jpdesigndev** [handsontable/react-handsontable#16]
I'm noticing considerable performance issues rendering a grid with ~30 rows in it. Initial render is taking ~900ms, and I need to render again after selection changes which also takes between ~500-900ms. These numbers are coming from the following code change I made to this component in `shouldComponentUpdate()`

```
var t1 = window.performance.now();
var settings = this.settingsMapper.getSettings(nextProps);
var t2 = window.performance.now();

console.log(`Settings took ${t2 - t1} milliseconds`); // < 1 millisecond

t1 = window.performance.now()
this.updateHot(settings);
t2 = window.performance.now();

console.log(`updateHot took ${t2 - t1} milliseconds`); // > 500ms / < 1000ms
```

I've never used Handsontable w/o React, but the demos don't appear to be slow. I'm afraid the `updateHot` method is not nearly as optimized as Handsontable itself. What sort of performance characteristics should I expect?

**Comment by jansiegel** [comment]
900ms for a selection doesn't sound too good. Could you prepare a simple demo with this problem (on [codepen](http://codepen.io/) for example), so I could take a look at it? 
Thanks!

**Comment by jpdesigndev** [comment]
I apologize for missing this response. Perhaps I'll get back to this sometime. Closed until I do so.
