### ISSUE TITLE
Double fixedBottomRow when when hotTable is surrounded by < > or <React.Fragment> with block elements

### ISSUE THREAD

**Issue by aninde** [handsontable/react-handsontable#170]
### Description
When you  embed the hotTable with <React.Fragment>  or in the short version with empy <> </> and make heading tags e.g. `<h2></h2>` fixedBottomRow is doubled and selection do not render corectly.

~In stable version displacement is very small, but on **currently test 7.4.0 shift is very big** so I mark this issue as a regression.~ EDIT: I have tested it locally with stable version. Behaviour is the same, so this is not a regression. 

The size of displacement changes with browsers. In Chrome is bigger then in Firefox.

### Steps to reproduce

1. Open demo https://codesandbox.io/s/react-fixed-19hxg
2. Select last row by clicking on last rowHeader.

**Chrome**
![Screenshot 2020-02-05 at 14 41 01](https://user-images.githubusercontent.com/30186818/73847282-3bf39e00-4826-11ea-8b6e-187b3dc33154.png)
**Firefox** 
![Screenshot 2020-02-05 at 14 30 54](https://user-images.githubusercontent.com/30186818/73847294-431aac00-4826-11ea-9d50-5c98d08f4ecf.png)
**Safari**
![Screenshot 2020-02-05 at 14 46 55](https://user-images.githubusercontent.com/30186818/73847350-62193e00-4826-11ea-9d31-673fb1baf44e.png)

### Case 2 
Tested locally with this [code](https://github.com/handsontable/quality/blob/test-projects/test-environments/react/my-app/src/App.js). The same behaviour is on 7.3.0 version.

![Screenshot 2020-02-05 at 14 42 02](https://user-images.githubusercontent.com/30186818/73847241-27afa100-4826-11ea-8a4c-32832b5a281c.png)

### Demo

https://codesandbox.io/s/react-fixed-19hxg

### Your environment
* React wrapper version: 3.1.2
* Handsontable version: any
* Browser Name and version: Firefox 72, Chrome 79
* Operating System: macOs

**Comment by aninde** [comment]
Another prn screen from 7.4.0 
```
hotSettings: {
        data: Handsontable.helper.createSpreadsheetData(5, 5),
        colHeaders: true,
        rowHeaders: true,
        fixedRowsTop: 2,
        fixedRowsBottom: 2,
        fixedColumnsLeft: 2,
        licenseKey: 'non-commercial-and-evaluation'
      }
```

Selection is double, row 3 is missing, last fixed row is double.
![Screenshot 2020-02-05 at 15 03 44](https://user-images.githubusercontent.com/30186818/73848687-dead1c00-4828-11ea-8f19-56babf822f2b.png)

**Comment by aninde** [comment]
#### Case 3 
When added instead of block element, element inline with block display this bug do occur.
Display inline-block does not cause this error.
```
 render() {
    return (
      <>
        <span id ="test">test</span>
        <HotTable settings={this.state.hotSettings}>
        </HotTable>
      </>
    );
  }
}
```
```
#test {
  display: block;
  margin-block: 5% 2%;
}
```
![Screenshot 2020-02-05 at 15 42 27](https://user-images.githubusercontent.com/30186818/73851738-4c0f7b80-482e-11ea-9a76-3b89f32a25cc.png)

**Comment by jansiegel** [comment]
I don't think it's a problem with `React.Fragment`, because it seems to work exactly the same with `<div>`:  https://codesandbox.io/s/react-fixed-8uk9n.

I also don't think it's a problem with the wrapper anyway, because it works even worse with the vanilla version: https://jsfiddle.net/L1rjuz3e/.

**Comment by aninde** [comment]
@jansiegel I'll check it locally once again.

**Comment by AMBudnik** [comment]
#### React
 (@jansiegel demo)
![react](https://user-images.githubusercontent.com/10757813/74135959-8c377b00-4bed-11ea-879a-bc18cfc88a38.png)

#### Vanilla 
(same settings as in the @jansiegel demo) https://codesandbox.io/s/dropdown-cell-type-source-change-k24ig
![image](https://user-images.githubusercontent.com/10757813/74136064-bc7f1980-4bed-11ea-95cd-bcd7f0c5b497.png)



Not sure if that was already reported but the autofill elements look odd on both versions on the 9th row.
#### React
![image](https://user-images.githubusercontent.com/10757813/74136337-239cce00-4bee-11ea-97ff-37614dc90aa6.png)
#### Vanilla
![image](https://user-images.githubusercontent.com/10757813/74136261-023be200-4bee-11ea-86f5-882a79aa63aa.png)

**Comment by jansiegel** [comment]
> Not sure if that was already reported but the autofill elements look odd on both versions on the 9th row.

They look kinda wonky, but I think we should create a separate issue on that (if it doesn't exist already) on the main Handsontable repo.

**Comment by AMBudnik** [comment]
@jansiegel true. I found that @aninde already reported it here https://github.com/handsontable/handsontable/issues/6348 so I will just update her topic with wrapper examples

**Comment by aninde** [comment]
I am closing the issue, because the problem also occurs in the vanilla version. This I have reported on https://github.com/handsontable/handsontable/issues/4454#issuecomment-584091552
