### ISSUE TITLE
Importing Numbro in React app with Handsontable/React do not work

### ISSUE THREAD

**Issue by aninde** [handsontable/react-handsontable#171]
### Description
How I can import Numbro to change culture of currency in react-app with Handsontable?
Pasting 
```
import numbro from 'numbro';
import languages from 'numbro/dist/languages.min.js';
```
in App.js code causes loop and crash. 

```
Starting the development server...
<--- Last few GCs --->
[20347:0x102883000]  49765 ms: Scavenge 2044.3 (2050.4) -> 2043.6 (2050.6) MB, 4.7 / 0.0 ms (average mu = 0.353, current mu = 0.357) allocation failure 
[20347:0x102883000]  52228 ms: Mark-sweep 2044.4 (2050.6) -> 2041.4 (2050.6) MB, 2423.4 / 0.0 ms (+ 36.1 ms in 12 steps since start of marking, biggest step 4.3 ms, walltime since start of marking 2463 ms) (average mu = 0.301, current mu = 0.256) alloc
<--- JS stacktrace --->
==== JS stack trace =========================================
  0: ExitFrame [pc: 0x10092fbd9]
  1: StubFrame [pc: 0x1008d1640]
Security context: 0x3996ced408a1 <JSObject>
  2: /* anonymous */(aka /* anonymous */) [0x39967ee003b1] [/Users/ndemytruk/Desktop/work/quality/test-environments/react/my-app/node_modules/@babel/core/lib/transformation/file/merge-map.js:~147] [pc=0x210b1f6d7d38](this=0x3996dea001b1 <null>,0x3996954b4929 <Object map = 0x399669466541>)
  3: forEach [0x3996ced51319](this...
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
Writing Node.js report to file: report.20200206.155728.20347.0.001.json
Node.js report completed
 1: 0x10007e743 node::Abort() [/Users/ndemytruk/.nvm/versions/node/v12.13.0/bin/node]
 2: 0x10007e8c7 node::OnFatalError(char const*, char const*) [/Users/ndemytruk/.nvm/versions/node/v12.13.0/bin/node]
 3: 0x100176267 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/ndemytruk/.nvm/versions/node/v12.13.0/bin/node]
 4: 0x100176203 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/ndemytruk/.nvm/versions/node/v12.13.0/bin/node]
 5: 0x1002fa2b5 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/ndemytruk/.nvm/versions/node/v12.13.0/bin/node]
 6: 0x1002fb984 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/Users/ndemytruk/.nvm/versions/node/v12.13.0/bin/node]
 7: 0x1002f8857 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/ndemytruk/.nvm/versions/node/v12.13.0/bin/node]
 8: 0x1002f683d v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/ndemytruk/.nvm/versions/node/v12.13.0/bin/node]
 9: 0x100301f54 v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/Users/ndemytruk/.nvm/versions/node/v12.13.0/bin/node]
10: 0x100301fcf v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/Users/ndemytruk/.nvm/versions/node/v12.13.0/bin/node]
11: 0x1002cebc7 v8::internal::factory::NewFillerObject(int, bool, v8::internal::AllocationType) [/Users/ndemytruk/.nvm/versions/node/v12.13.0/bin/node]
12: 0x1005f7725 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/ndemytruk/.nvm/versions/node/v12.13.0/bin/node]
13: 0x10092fbd9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/ndemytruk/.nvm/versions/node/v12.13.0/bin/node]
14: 0x1008d1640 Builtins_ArraySingleArgumentConstructor_HoleySmi_DisableAllocationSites [/Users/ndemytruk/.nvm/versions/node/v12.13.0/bin/node]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-app@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!   /Users/ndemytruk/.npm/_logs/2020-02-06T14_57_28_058Z-debug.log
```

### Steps to reproduce

1.  npx create-react-app my-app
2.cd my-app
3. npm install handsontable @handsontable/react 
4. npm install numbro
5. npm start

### Demo

Tested locally with
https://github.com/handsontable/quality/blob/test-projects/test-environments/react/my-app/src/App.js
https://github.com/handsontable/quality/commit/9179c7e87ce6eacf31378893380f38864fb2d719

### Your environment
* React wrapper version: 3.1.2
* Handsontable version: 7.3.0 and 7.4.0
* Browser Name and version: not related
* Operating System: macOs

**Comment by pnowak** [comment]
When I copied your app (and slightly change the order in the import section) to codesandbox I hadn't any problem - https://codesandbox.io/s/importing-numbro-in-react-app-with-handsontablereact-dy281
And in console you could see `languages` object.

**Comment by aninde** [comment]
@pnowak thank you very much. Probably this problem results from my application. In your demo, I can see that despite the fact that the table is rendering still currency formatting does not work. This column should be in euros. Overlapping of the fixed column results from the codeSandbox css.
![Screenshot 2020-02-06 at 16 41 43](https://user-images.githubusercontent.com/30186818/73953325-85b0b700-4900-11ea-8325-e54c8a37ec5a.png)

**Comment by jansiegel** [comment]
@aninde 
1. I don't have any problems with running the app, maybe try creating a new react app from scratch?
2. You don't have to install `numbro` separately, it's a handsontable dependency, so it'll install itself in the supported version.
3. In this scenario, you're testing the wrapper against HOT `7.3.0`, not `7.4.0` release candidate, I don't know if that's intentional?

<br>

As for the currency formatting, there are two things:
1. In your app, you're defining the currency as `languages`:
```
numericFormat: {
    pattern: '0,0.00 $',
    languages: 'de-DE'
}
```
[while it should be defined as `culture`](https://handsontable.com/docs/7.3.0/demo-numeric.html):
```
numericFormat: {
    pattern: '0,0.00 $',
    culture: 'de-DE'
}
```
that's why it doesn't work in @pnowak's codesandbox example based on your `App.js`.

2. There's this thing with `numbro`'s languages, that they need to be registered before use. (see this issue on `numbro`'s repo: https://github.com/BenjaminVanRyseghem/numbro/issues/388). Adding a snippet which auto-registers all imported languages:
```
Object.values(languages).forEach((l) => numbro.registerLanguage(l));
```
makes the currencies work fine.

Here's an updated codesandbox example: https://codesandbox.io/s/importing-numbro-in-react-app-with-handsontablereact-5yshz

**Comment by aninde** [comment]
@jansiegel thank you very much. 

>     1. I don't have any problems with running the app, maybe try creating a new react app from scratch?

I'll do it again locally.

>     2. You don't have to install `numbro` separately, it's a handsontable dependency, so it'll install itself in the supported version.

Without installing `numbro` I had problems in my local version, but maybe it was the application's fault.

>     3. In this scenario, you're testing the wrapper against HOT `7.3.0`, not `7.4.0` release candidate, I don't know if that's intentional?

I know. Locally I have it in version 7.4.0. I installed it  according to your idea through `npm install pack-with-7.4.0 @handsontable/react`
