### ISSUE TITLE
The editor won’t open with a double click

### ISSUE THREAD

**Issue by TankTwo2** [handsontable/react-handsontable#173]
### Description
I have built the server with React & nextJS and used next/dynamic to use “handsontable”.
I succeeded rendering handsontable on the screen but the editor does not open with mouse double click.
Could you please provide me a solution for this?

### Steps to reproduce

1.
2.
3.

### Demo

`import { useSelector, useDispatch } from 'react-redux';
import {Button, Box} from '../../components/meterial'

import dynamic from 'next/dynamic';
const SheetTable = dynamic(
	() => import('../../components/SheetTable'),
	{ ssr: false }
);

const testtable = () => {
	const dispatch = useDispatch();
	let temp = ['https://handsontable.com/docs/7.4.0/frameworks-wrapper-for-react-custom-renderer-example.html', 'Tesla', 'Volvo', 'Toyota', 'Ford',6,7,8,9,10,11,12,13,14,15,16,17,18,19,20];
	let temp2 = ['',7,8,9,10,11,',6,7,8,9,10,11,12,13,14,15,16,17,18,19,20];

	let data2 = [
		[...temp],[...temp2],  [...temp], [...temp2]
	];

	let count = 0;

	const [loadData, saveData] = useState(data2);

	useEffect(()=>{console.log(loadData)},[loadData]);

	return ( <>
			<button onClick={()=>{console.log(loadData)}}>test</button>
			<Button variant="contained" color="primary">
				Hello World
			</Button>
			<SheetTable data={data2}
			            opt={
				{
					data:data2,
					colHeaders: true,
					rowHeaders: true,
					stretchH: "all",
					allowEmpty: true,
					fillHandle: true,
					columnSorting: true,
					sortIndicator: true,
					dropdownMenu: [ 'undo', 'redo', '---------',  "filter_by_condition", "filter_operators", "filter_by_condition2", "filter_by_value", "filter_action_bar"],
					filters: true,
					viewportRowRenderingOffset: 70,
					viewportColumnRenderingOffset: 30,
					// contextMenu: true,
					// hiddenRows:{ columns: [3, 5, 9], }
				}
				           
			}
			/>

		</>
	)
};

testtable.getInitialProps = async (context) => {

};
export default testtable;`

### Your environment
* Handsontable version: 7.4.0
* Browser Name and version: chrome 80.0.3987.106
* Operating System: Mac

**Comment by mirkogeest** [comment]
Thx Aleksandra. It seems this bug started with version 7.2.0

**Comment by AMBudnik** [comment]
You're right @mirkogeest 

It worked well in `7.1.1` and there is no improvement in any newer version of Handsontable.

**Comment by AMBudnik** [comment]
Update. I've used our demo and cleared it up https://codesandbox.io/s/importing-numbro-in-react-app-with-handsontablereact-hdou9 it works well, so I guess that the use structure makes it work differently. Once you use the Handsontable wrapper it works OK.

**Comment by wojciechczerniak** [comment]
@AMBudnik @mirkogeest You're using new Handsontable JS with old CSS. Please update both.

https://codesandbox.io/s/react-handsontable-web-worker-y7byo?file=/src/index.js

**Comment by mirkogeest** [comment]
Thank you Wojciech!

**Comment by mirkogeest** [comment]
> @AMBudnik @mirkogeest You're using new Handsontable JS with old CSS. Please update both.
> 
> https://codesandbox.io/s/react-handsontable-web-worker-y7byo?file=/src/index.js

Thank you @wojciechczerniak !!

**Comment by AMBudnik** [comment]
Great. I guess that we can close the topic. Thanks for the hint @wojciechczerniak

**Comment by HienDoanTan** [comment]
> @AMBudnik @mirkogeest You're using new Handsontable JS with old CSS. Please update both.
> 
> https://codesandbox.io/s/react-handsontable-web-worker-y7byo?file=/src/index.js

thanks you bro!!
