### ISSUE TITLE
issue on first load 

### ISSUE THREAD

**Issue by mx2323** [handsontable/react-handsontable#177]
### Description
when my react app using HandsOnTable first loads, the table looks like this. the row headers are way larger than the rows. 
![image](https://user-images.githubusercontent.com/528124/77484190-85f10d00-6def-11ea-8f9a-8fb390bfce1b.png)

for whatever reason, its setting the height to '86px'

![image](https://user-images.githubusercontent.com/528124/77484375-01eb5500-6df0-11ea-8661-fa5d72c7476c.png)

after a bit of scrolling up and down, it reverts to looking correct. 

![image](https://user-images.githubusercontent.com/528124/77484205-91443880-6def-11ea-97f5-87f14936a266.png)
![image](https://user-images.githubusercontent.com/528124/77484402-12033480-6df0-11ea-9438-75a93f70d375.png)

it only happens on the first load of a table in the app, even if i trigger some actions that remove and remount the table, the table looks fine. its only on the first time a table loads in the app that this happens. 

### Steps to reproduce
not sure how i could make a reproducible test case outside of my app. 

### Your environment
* React wrapper version:     "^3.1.2",

* Handsontable version:^7.4.2
* Browser Name and version: mac OS x & chrome
* Operating System: mac os x

**Comment by pnowak** [comment]
Hi @mx2323 

Could you share with us a working demo? 
It is much easier to find a solution in that way.

Here is a demo that you can use to pass your code - https://codesandbox.io/s/fetch-data-1bk6y

Thanks in advance.
