### ISSUE TITLE
dataMap null after using `setState` in hook function, causes TypeError

### ISSUE THREAD

**Issue by febeling** [handsontable/react-handsontable#18]
After the 'afterRemoveRow' hook has run this TypeError comes up:

`Uncaught TypeError: Cannot set property 'forceFullRender' of null`

Version 0.2.1

```
DataMap.removeRow	@	handsontable.js?732b:6878
alter	@	handsontable.js?732b:4815
Core.alter	@	handsontable.js?732b:5875
callback	@	handsontable.js?732b:16321
(anonymous)	@	handsontable.js?732b:14695
arrayEach	@	handsontable.js?732b:9907
execute	@	handsontable.js?732b:14694
executeCommand	@	handsontable.js?732b:14854
(anonymous)	@	handsontable.js?732b:14806
(anonymous)	@	handsontable.js?732b:11990
arrayEach	@	handsontable.js?732b:9907
runLocalHooks	@	handsontable.js?732b:11989
executeCommand	@	handsontable.js?732b:15320
onDocumentMouseDown	@	handsontable.js?732b:15597
(anonymous)	@	handsontable.js?732b:15169
callbackProxy	@	handsontable.js?732b:9634
```
Location of error (debugger view):
```
DataMap.prototype.removeRow = function(index, amount, source) {
  if (!amount) {
    amount = 1;
  }
  if (typeof index !== 'number') {
    index = -amount;
  }
  amount = Handsontable.hooks.run(this.instance, 'modifyRemovedAmount', amount, index);
  index = (this.instance.countSourceRows() + index) % this.instance.countSourceRows();
  var logicRows = this.physicalRowsToLogical(index, amount);
  var actionWasNotCancelled = Handsontable.hooks.run(this.instance, 'beforeRemoveRow', index, amount, logicRows, source);
  if (actionWasNotCancelled === false) {
    return;
  }
  var data = this.dataSource;
  var newData;
  newData = this.filterData(index, amount);
  if (newData) {
    data.length = 0;
    Array.prototype.push.apply(data, newData);
  }
  Handsontable.hooks.run(this.instance, 'afterRemoveRow', index, amount, logicRows, source);
  this.instance.forceFullRender = true; 
};
```

Error thrown in the second to last line: `  this.instance.forceFullRender = true; `

**EDIT**: What this problem looks like to me: After using `setState` in a hook function the dataMap loses it's HOT instance. Both errors are due to missing HOT instance. It sounds plausible to me that setting state could have that effect, making the component state inconsistent with what HOT assumes.

**Comment by febeling** [comment]
Similar error when using `beforeRemoveRow` hook:

```
DataMap.prototype.physicalRowsToLogical = function(index, amount) {
  var totalRows = this.instance.countSourceRows(); // <-- from this line
  var physicRow = (totalRows + index) % totalRows;
  var logicRows = [];
  var rowsToRemove = amount;
  var row;
  while (physicRow < totalRows && rowsToRemove) {
    row = Handsontable.hooks.run(this.instance, 'modifyRow', physicRow);
    logicRows.push(row);
    rowsToRemove--;
    physicRow++;
  }
  return logicRows;
};
```
This error: 

```
Uncaught TypeError: Cannot read property 'countSourceRows' of null
    at DataMap.physicalRowsToLogical (eval at <anonymous> (application.js:4091), <anonymous>:7044:32)
    at DataMap.filterData (eval at <anonymous> (application.js:4091), <anonymous>:6962:24)
    at DataMap.removeRow (eval at <anonymous> (application.js:4091), <anonymous>:6872:18)
    at Object.alter (eval at <anonymous> (application.js:4091), <anonymous>:4815:19)
    at Core.alter (eval at <anonymous> (application.js:4091), <anonymous>:5875:10)
    at Core.callback (eval at <anonymous> (application.js:4091), <anonymous>:16321:12)
    at eval (eval at <anonymous> (application.js:4091), <anonymous>:14695:23)
    at arrayEach (eval at <anonymous> (application.js:4091), <anonymous>:9907:9)
    at CommandExecutor.execute (eval at <anonymous> (application.js:4091), <anonymous>:14694:5)
    at ContextMenu.executeCommand (eval at <anonymous> (application.js:4091), <anonymous>:14854:34)
```

**Comment by febeling** [comment]
The problem only occurs if the hook function run `setState` on the data source, it seems.

**Comment by jansiegel** [comment]
@febeling, first of all, thanks for the detailed problem description, it helped a lot.
The problem occurs because `setState` calls the `shouldComponentUpdate` method, which calls Handsontable's `updateSettings`, resulting in "resetting" the handsontable instance, while still processing the plugin hooks of the "old" instance.

I'll try to figure something out eventually, but for now I think you might try calling `setState` asynchronously - this way the "old" instance should be able to finish calling all the hooks before being updated.

Take a look at this example: https://codepen.io/js-ziggle/pen/awryaY?editors=0010

**Comment by febeling** [comment]
@AMBudnik Is there additional info about this? Was there a fix?

**Comment by AMBudnik** [comment]
Hi @febeling 

please check https://github.com/handsontable/react-handsontable/commit/53b21665c610c50f41f2f778fe5ecaa5e6a11fcd

**Comment by warpech** [comment]
Note that this solution applies to most of the Handsontable hooks. If you want to change the state of your React app (by changing the React component's state, props, hooks, etc), it is recommended to do that asynchrously as presented in the above pen (https://codepen.io/js-ziggle/pen/awryaY?editors=0010)
