### ISSUE TITLE
Unsafe component lifecycles in strict mode

### ISSUE THREAD

**Issue by InsidersByte** [handsontable/react-handsontable#184]
### Description

Warnings for unsafe component lifecycles https://fb.me/react-unsafe-component-lifecycles in strict mode

### Steps to reproduce

1. Enable strict mode (https://reactjs.org/docs/strict-mode.html)
2. Render HotTable
3. Look at the development console for errors (see below)

### Your environment
* React wrapper version: 3.1.3
* Handsontable version: 7.4.2
* React version: 16.13.1

![image](https://user-images.githubusercontent.com/6938575/84017349-6e4d0d80-a976-11ea-8d33-33d094c5adb1.png)

**Comment by pnowak** [comment]
Yes, we aware of these warnings.

We need some time to rewrite our wrapper. 
So until we rewrite, we must use `UNSAFE_`.
