### ISSUE TITLE
Custom hot-editor component doesn't stick to a cell when scrolling.

### ISSUE THREAD

**Issue by Freakazo** [handsontable/react-handsontable#186]
### Description
When extending the base Editor Class to implement a custom editor with React, the editor does not scroll with the cell.

getEditedCell can return a td element with different data than the cell being edited.

Providing methods for finding the position of the cell being edited, or the cell being edited would be very valuable.

### Steps to reproduce
Create a HoT with a limited height and enough data to enable scrolling.

I added a watch method to the component to try and use request animation frame, but that produces strange behaviour since it seems like the td gets replaced with data for other fields.

### Demo
https://codesandbox.io/s/declaring-a-custom-editor-as-a-component-35v2i?file=/src/editorComponent.jsx

### Your environment
* React wrapper version:
* Handsontable version: 7.3.0/3.1.3
* Browser Name and version: Chrome
* Operating System: Linux

**Comment by AMBudnik** [comment]
In that case, we have the same behavior as it is for the context menu https://jsfiddle.net/AMBudnik/oatv5rg6/ so the fact that this is an external DIV might be inheriting the CSS settings.

**Comment by wojciechczerniak** [comment]
This depends on where you append your editor container. If it's inside hot root element, then it will scroll. It may not be the best user experience though. Editors inside scrollable container will be cut by the overflow.

That's why the context menu is fully visible but attached to fixed position.
