### ISSUE TITLE
Two way data binding - updates are resetting change history

### ISSUE THREAD

**Issue by melloc01** [handsontable/react-handsontable#188]
### Description
I created a wrapper for the lib where I wanted to have two way data binding, to treat it like a native form input where I could pass `value` and `onChange` props and get the DOM (HotInstance) state in sync with the prop `value`.

I am using the `afterChangesObserved` hook to get the changes and to also be safe of infinite loops.

### Steps to reproduce

1. Change the table data
2. Try to "undo"
3. Changes are not undone

### Demo
https://codesandbox.io/s/hottable-2-way-data-binding-corid?file=/src/MyWrapper.js

### Your environment
* React wrapper version: 3.1.3
* Handsontable version: 6.2.2

**Comment by pnowak** [comment]
Hi @melloc01 

First of all, we decided that `observeChanges` plugin is deprecated. In version 8.0.0 you get a console warning. Here is an epic in our repo - https://github.com/handsontable/handsontable/issues/6465
So I don't recommend to based on this plugin.

Furthermore, you use `state` so you have to hold the `undoRedo` functionality by yourself. 
This is why you can't use our `undoRedo`.

You can consider using an existing library - https://github.com/omnidan/redux-undo.
Or you could look at how to approach this problem. 
This is, for instance, a redux tutorial - https://redux.js.org/recipes/implementing-undo-history
So, on the one hand, you could store the entire state object as the present, past, and future.

On the other hand, you could use Immer which just store details about what has changed. Here is a tutorial to implement Undo-Redo Functionality using Immer  - https://techinscribed.com/implementing-undo-redo-functionality-in-redux-using-immer/?utm_source=stackoverflow&utm_medium=referral&utm_campaign=stackoverflow_answering
