### ISSUE TITLE
Memoization using Pure components

### ISSUE THREAD

**Issue by underfisk** [handsontable/react-handsontable#193]
### Description
The current implementation re-renders too often even when Props are equal, at least we should have a PureComponent or props compare with shouldComponentUpdate lifecycle and that's a huge issue if the parent of Handsontable React wrapper re-renders but the props of the wrapper are equal.
There is a demo showing that only updating the state is making the Handsontable invoke its lifecycles and re-render when there is no need, the data is still equal and so does the references

### Steps to reproduce

1. Wrap Handsontable React into a parent and perform multiple updates on the parent as updating a state
2.Review that Handonstable wrapper gets re-rendered even though props are equal
3. Updating an internal state on the parent will also provoke this
4. Ofc if internal state provokes the re-render, props for the parent would also trigger
### Demo

https://jsfiddle.net/jaskile12/2L9e5p31/

### Your environment
* React wrapper version: v4
* Handsontable version:v8
* Browser Name and version: Any
* Operating System: Any

**Comment by AMBudnik** [comment]
Thank you for sharing this improvement suggestion. I think that it will be much easier to provide this functionality after releasing the v8 for Handsontable. I'll notify you once this suggestion makes it's way to the Roadmap.

**Comment by underfisk** [comment]
This feature is quite easy and it's a huge improvement for who's using React, I think it could be considered an important thing because so far this is the basic optimization for the wrapper.
If you could prioritize this, it would be really great because I'm sure it would help a lot in general

**Comment by underfisk** [comment]
@AMBudnik Any news regarding this? Support for React seems stuck and in my organization, it is a crucial piece which right now we can't leverage too much of Handsontable except being optimizing at all costs
This feature does not take much time and it would be great to see some support from the team

**Comment by AMBudnik** [comment]
There is no news yet @underfisk. I appreciate your feedback and will make sure to notify you once we move on with any updates to the React wrapper.

**Comment by underfisk** [comment]
@AMBudnik It is quite crucial for us having a good support on this, the plugin itself works good but the support is still not that great
Also is there any updates regarding react components/functions as renderers? We need some renderers with lifecycle, for example a simply thing as a div wrapped by a tooltip component (Material-UI in this case) and right now we can't even do that simple thing because there is no way of having our cells with react component/functions

**Comment by AMBudnik** [comment]
> Also is there any updates regarding react components/functions as renderers?

Since the update of v8.0.0, we did not plan any bigger changes, we are taking this time to clean documentation and do website-related tasks. We should have a new Roadmap soon.

**Comment by underfisk** [comment]
@AMBudnik I'm kinda worried about this situation because right now we have some components that heavily depend upon the team support for React
