### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by truztee** [handsontable/react-handsontable#2]
It seems that if we use a hook with the hot table instance the instance will still be active in memory even if the parent component has already unmounted, calling `hotInstance.destroy()` in componentWillUnmount should fix this.

**Comment by jansiegel** [comment]
@truztee You're probably right! Thanks for noticing it, It'll be fixed soon.

**Comment by jansiegel** [comment]
@truztee The change needed for this is released in version `0.2.0`. Does it fix the problem for you?

**Comment by luthv** [comment]
yes thanks for the fix

**Comment by truztee** [comment]
oops sorry for that, I didn't realize that I was using another account.

yes it fix the problem, I can remove my own destroy call in my component now.

**Comment by ddebarros** [comment]
You should check if the hotInstance exists before calling the destroy function.
`componentWillUnmount() {
    if (this.hotInstance) {
        this.hotInstance.destroy();
    }
  }`
