### ISSUE TITLE
beforeInit event is not working

### ISSUE THREAD

**Issue by pflaumingo** [handsontable/react-handsontable#20]
I'm unable to get the beforeInit event to fire when using the react-handsontable wrapper. Adding the below setting to this [codepen](https://codepen.io/handsoncode/pen/ygvaxv?editors=0010) implementation doesn't trigger anything.

beforeInit = {function() {console.log("beforeInit")}}

Are certain events not available in this wrapper?

**Comment by jansiegel** [comment]
The `beforeInit` hook is a tricky one, as it is triggered before initializing the Handsontable instance, which means, also before setting up hook callbacks from the HOT settings.
So it's not exactly a wrapper issue, more like a design thing.
