### ISSUE TITLE
[8.1.0] Using setDataAtRowProp on prop not on table issue

### ISSUE THREAD

**Issue by RanaOsamaAwadallah** [handsontable/react-handsontable#202]
### Description
Hello,
Been using handsontable for almost a year now and I have a usecase where my data is an array of objects and I don't want to display some feilds on the table but I want to edit them.
Note: I don't want to use hidden columns as I need to show some hidden columns when exporting to csv and don't want those to appear.

I was able to do that prior to V8.0.0 & V8.1.0
I was also able to that in V8.0.0-beta.1

### Demo
Simplified version of my usecase:
**Working** version 7.4.2 demo https://jsfiddle.net/0z5kvbxd/
**Working** version 8.0.0-beta.1 https://jsfiddle.net/0z5kvbxd/1/
**Broken** version 8.1.0 demo https://jsfiddle.net/eafbtj1r/

### Your environment
* React wrapper version: 4.0.0
* Handsontable version: 8.1.0
* Browser Name and version: Chrome
* Operating System: Windows 10

**Comment by RanaOsamaAwadallah** [comment]
Update:
Fails at 
function validateChanges (line 392840)
----> var cellProperties = instance.getCellMeta(row, col);
Error: Assertion failed: Expecting an unsigned number.

in 8.0.0-beta.1 var cellProperties = priv.cellSettings[physicalRow][physicalColumn];

**Comment by wojciechczerniak** [comment]
@RanaOsamaAwadallah To modify source data that is not displayed you should use `setSourceDataAtCell`.

**Comment by RanaOsamaAwadallah** [comment]
@wojciechczerniak Tried using it but I need to use the source as well. 
So I tried setSourceDataAtCell(arrOfChanges, source)
What I get in setSourceDataAtCell is an undefined source

**Comment by wojciechczerniak** [comment]
Thats because `source` is the 4th argument: `setSourceDataAtCell(arrOfChanges, undefined, undefined, source)`

**Comment by RanaOsamaAwadallah** [comment]
I see, I was able to do that with setDataAtRowProp so assumed it'd be the same.

Thanks for the help, all seems good now.

**Comment by wojciechczerniak** [comment]
No problem, thanks for reporting the inconsistency

@AMBudnik Can you investigate this? The feature is in the code, but not documented. Although, it's defined in `d.ts`

https://github.com/handsontable/handsontable/blob/b7618fc4213d3b2ab32ba62ff6f1d57cd1af6c49/handsontable.d.ts#L121-L126

Maybe a feature request for API consistency? And should we fix the docs? CC @scarletfog
