### ISSUE TITLE
[8.1.0] RangeError: toFixed() digits arguments must be between 0 and 100

### ISSUE THREAD

**Issue by RanaOsamaAwadallah** [handsontable/react-handsontable#203]
### Description
I get a "RangeError: toFixed() digits arguments must be between 0 and 100" error when trying to load the table.

![image](https://user-images.githubusercontent.com/15252406/97456823-df02bf80-1941-11eb-958a-4bd4b9dd1b10.png)

This might be relevant to this issue: https://github.com/handsontable/handsontable/issues/5790
as 8.1.0 has numbro v 2.1.2 in its dependencies. 

### Your environment
* React wrapper version: 4.0.0
* Handsontable version: 8.1.0
* Browser Name and version: Chrome
* Operating System: Windows

**Comment by AMBudnik** [comment]
Thank you for sharing @RanaOsamaAwadallah 

That's true. We've fixed the Numbro 2.1.1 https://github.com/handsontable/handsontable/pull/5912/files but Handsontable 8.1.0 loads Numbro 2.1.2 https://github.com/handsontable/handsontable/blob/master/package.json#L78
![Zrzut ekranu 2020-10-29 o 11 16 53](https://user-images.githubusercontent.com/10757813/97555312-43705e00-19d8-11eb-81b0-d7c7fc4bfc80.png)

**Comment by wojciechczerniak** [comment]
@RanaOsamaAwadallah The problem was not with Numbro, but with Webpack minification plugin that is using Terser. The issue was fixed in version 4.1.3 that was released in Aug 2019, over a year ago. That's why we've updated the dependency. Problem was with the build pipeline. What are you using to minify your app? Which versions? Can you update?

**Comment by RanaOsamaAwadallah** [comment]
@wojciechczerniak aha I see. 
My react-scripts version is 3.0.1 which runs an old version of terser (probably prior to the fix)
I'll update it to latest (v4.0.0) once they fix the blocking TS issues and update here once all's good
Thanks for the help!

**Comment by wojciechczerniak** [comment]
If you're using our ES or CommonJS build then it should be possible to force Handsontable to use older version of Numbro with Webpack module aliasing. Install `npm numbro@2.1.1` and force all imports to use `numbro` from your app:

```js
// webpack.conf
  resolve: {
    alias: {
      numbro: path.resolve(__dirname, 'node_modules/numbro')
    }
  }
```
