### ISSUE TITLE
Handsontable Not Showing up on Component Load

### ISSUE THREAD

**Issue by ankitgoyal100** [handsontable/react-handsontable#205]
### Description
Handsontable component does not show up when a component is loaded. This is what it looks like when a component is first loaded:
<img width="512" alt="Screen Shot 2020-11-23 at 11 17 57 AM" src="https://user-images.githubusercontent.com/3400675/99986865-bec9f300-2d7d-11eb-86fa-48123f76401a.png">

This is what it looks like once I click the grey cell that is in the above screenshot:
<img width="505" alt="Screen Shot 2020-11-23 at 11 18 03 AM" src="https://user-images.githubusercontent.com/3400675/99986920-cab5b500-2d7d-11eb-9cd2-6a2404243667.png">

How do I configure the table so it shows up expanded when the component is first loaded? 

### Your environment
* React wrapper version: 4.0.0
* Handsontable version: 8.2.0

**Comment by AMBudnik** [comment]
Hi @ankitgoyal100 

do you use any external CSS or a CSS framework? I see that the font of Handsontable changed so I assume that something more than the handsontable.css is added to the project. If so, you should check properties related to position and overflow.

**Comment by ankitgoyal100** [comment]
Hi @AMBudnik I'm using React Bootstrap and nothing else. Would you be open to a quick 15 min call to discuss this issue?
