### ISSUE TITLE
Error with Custom Renderers in React

### ISSUE THREAD

**Issue by ankitgoyal100** [handsontable/react-handsontable#207]
Hi, I'm running into the following issue with custom renderers in React:

### Code
```
if (typeof value === "boolean" || value == null) {
  // @ts-ignore
  return Handsontable.renderers.CheckboxRenderer.apply(this, arguments);
}

// @ts-ignore
return Handsontable.renderers.TextRenderer.apply(this, arguments);
```

### Error
<img width="1021" alt="Screen Shot 2020-11-30 at 9 32 10 PM" src="https://user-images.githubusercontent.com/3400675/100689986-9d57a100-3353-11eb-8d93-e4ae214139b8.png">

### Your environment
* Handsontable version: 8.2.0

**Comment by AMBudnik** [comment]
I guess that we can call this issue solved (we've discussed that with @ankitgoyal100 on emails).
