### ISSUE TITLE
Uncaught error using React basic demo with Typescript

### ISSUE THREAD

**Issue by pabloimrik17** [handsontable/react-handsontable#210]
### Description
Hi, im trying to render a very basic HotTable to test the performance of the library, and using the very basic demo the app is crashing.

### Steps to reproduce

1. render the component
2. Go to the app
3. Check console error

### Demo

https://jsfiddle.net/handsoncode/c6rgz08x/
![image](https://user-images.githubusercontent.com/5611863/102812208-f2248f80-43c6-11eb-8e63-2926c7563454.png)
![image](https://user-images.githubusercontent.com/5611863/102812229-f94b9d80-43c6-11eb-833a-56b707636ec8.png)
![image](https://user-images.githubusercontent.com/5611863/102812252-01a3d880-43c7-11eb-9cc0-52a4c33884ec.png)
![image](https://user-images.githubusercontent.com/5611863/102812422-4465b080-43c7-11eb-9681-d1eb1d7cf18e.png)
![image](https://user-images.githubusercontent.com/5611863/102812465-52b3cc80-43c7-11eb-9da5-940d5e8f3746.png)

### Your environment
* React wrapper version: 4.0.0
* Handsontable version: 8.2.0
* React: 16.13.1
* Typescript 4.0.3

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report. Pablo. I've built a sample app using 

> npx create-react-app my-app --template typescript

with following dependencies

```
    "@handsontable/react": "^4.0.0",
    "@types/react": "^16.9.53",
    "handsontable": "^8.2.0",
    "react": "^17.0.1",
    "typescript": "^4.0.3",
```
and got the project working. You can download it from here (_node_modules_ removed) https://we.tl/t-UzfQxXJWaW 

ps. we've created a separate project to test Handsontable performance https://github.com/handsontable/performance-lab
We mostly use it to compare two versions of the software but if you want to test it you just pick a set of settings for the table as all the crucial test scenarios are already defined and available to run.

**Comment by pabloimrik17** [comment]
Thanks for the demo and the fast reply, i spent some time trying to figure out what the source of the problem is, and i found this code from my project:

![image](https://user-images.githubusercontent.com/5611863/102906111-76811c00-4474-11eb-9e67-94459786c384.png)

After i rename that custom function to something else, everything is working. Just in case you want to review that.
