### ISSUE TITLE
HotColumn example not working with isHotColumn returning false

### ISSUE THREAD

**Issue by shawnxusy** [handsontable/react-handsontable#211]
### Description
I ported over the basic example (https://codesandbox.io/s/object-data-source-forked-icfpv) to my local dev environment, and it does not render the custom renderers as it should. Also tried a couple other examples and none working.

This is my code snippet:
```
import React from 'react';
import { HotTable, HotColumn } from '@handsontable/react';
import "handsontable/dist/handsontable.min.css";

const ScoreRenderer = props => {...}  // same as codesandbox example
const PromotionRenderer = props => {...}   // same as codesandbox example
 
function Test() {
  const settings = {...} // same as codesandbox example
  return (
    <HotTable settings={settings}>
      <HotColumn data="id" />
      <HotColumn data="name" />
      <HotColumn data="score">
        <ScoreRenderer hot-renderer />
      </HotColumn>
      <HotColumn data="isPromoted">
        <PromotionRenderer hot-renderer />
      </HotColumn>
    </HotTable>
  );
}

```

This is what gets rendered, notice color and icons are not correctly rendered:
![image](https://user-images.githubusercontent.com/1550598/103106303-24add280-45e9-11eb-92f5-dcfb21839d87.png)

However, if I go to `react/es/react-handsontable.js` and change the following:
```
 var isHotColumn = function isHotColumn(childNode) {
        // return childNode.type === HotColumn
        return true; // always return true
      };
```
It works all fine with color/icons rendered.

### Demo
I can't reproduce it on cloud sandbox unfortunately, and suspecting it has something to do with modules and exports, but no way to confirm it.

### Your environment
* React wrapper version: 4.0.0
* Handsontable version: 8.2.0
* Browser Name and version: Chrome 87.0.4280
* Operating System: OSX Catalina

**Comment by warpech** [comment]
It seems that the problem is not just with custom renderers but with `HotColumn` in general. It seems that the function `isHotColumn` in `@handsontable/react` and your code use a different identity of the `HotColumn` class.

I have a few questions:

1. What bundler version do you use?
   - I am not saying it only works with one setup, but for reference, CodeSandbox uses [create-react-app](https://github.com/facebook/create-react-app) to build the sandbox app, which in its newest version uses Webpack 4.44.2 + Babel 7.12.3
2. Just for reference, do you use TypeScript in your project?
3. Did you make any customizations to `@handsontable/react`?

-----

At this point, I can't propose a solution yet, but I have an idea. In your project, try the below ways of importing, one by one. Maybe one of them will work:

```js
//import { HotTable, HotColumn } from "@handsontable/react";
import { HotTable, HotColumn } from "@handsontable/react/es/react-handsontable";
//import { HotTable, HotColumn } from "@handsontable/react/commonjs/react-handsontable";
//import { HotTable, HotColumn } from "@handsontable/react/dist/react-handsontable";
```

Please let me know if any of the imports worked.

------

Below, I will continue to explain the different bundles, because it seems to me that a bundler mixes them up.

The `@handsontable/react` NPM module contains 3 different bundles: `dist`, `es`, `commonjs`. 

I can observe a similar problem to yours when I import `HotTable` and `HotColumn` from different bundles (https://codesandbox.io/s/object-data-source-forked-izd87):

```txt
import { HotTable } from "@handsontable/react/es/react-handsontable";
import { HotColumn } from "@handsontable/react/commonjs/react-handsontable"; // does not work, because of the mixed bundles
```

The problem is gone when both are imported from the same bundle (https://codesandbox.io/s/object-data-source-forked-4qlvo?file=/src/index.js):

```js
import { HotTable } from "@handsontable/react/es/react-handsontable";
import { HotColumn } from "@handsontable/react/es/react-handsontable"; // works
```

```js
import { HotTable } from "@handsontable/react";
import { HotColumn } from "@handsontable/react/es/react-handsontable"; // also works, at least in CodeSandbox
```

```txt
import { HotTable } from "@handsontable/react";
import { HotColumn } from "@handsontable/react/commonjs/react-handsontable"; // does not work, because of the mixed bundles
```

**Comment by shawnxusy** [comment]
Thanks @warpech for replying.

I was suspecting it was a bundler issue, and also tried the other imports (es / commonjs / dist), but none seems to work.

From what I experimented, the bundler finds the es module correctly. Here's what I did to find out: 
- Go to `es/react-handsontable`
- In function
```
var isHotColumn = function isHotColumn(childNode) {
        return childNode.type === HotColumn;
      };
```
I changed it to `return true`
- Reload page, now the display shows all fine.
- Changing it back and reloads page, display is not correct again.



As for the other questions:
1. I'm using Webpack 4.44.2 + babel 7.7.7
2. I don't use Typescript
3. I didn't make any customizations to `@handsontable/react`, except for the little experiment above which I cleared.

**Comment by AMBudnik** [comment]
Hi,

I've just built an app with the React CLI and loaded what's in the https://codesandbox.io/s/object-data-source-forked-icfpv and it works well on my Windows 10/ Chrome 87.

![react](https://user-images.githubusercontent.com/10757813/103624601-0bd2e480-4f3a-11eb-88cf-006d205cc0f9.png)

Here's the project
.zip https://we.tl/t-ho6WWOEFXO (_node_modules_ removed)


```
"@handsontable/react": "^4.0.0",
"handsontable": "^8.2.0",
"react": "^17.0.1",
```

**Comment by shawnxusy** [comment]
Also, in react/es/react-handsontable.js, 
changing 
```
var isHotColumn = function isHotColumn(childNode) {
        return childNode.type === HotColumn;
      };
```
to
```
 var isHotColumn = function isHotColumn(childNode) {
        return childNode.type.toString() === HotColumn.toString();
      };
```

works for me. Any idea why this is the case? I really hope not to clone & customize the lib.

**Comment by AMBudnik** [comment]
Can you send over your package.json file, @shawnxusy ?

**Comment by shawnxusy** [comment]
@AMBudnik sure!
here it is (removed the ones that are possibly not relevant):
```
 "dependencies": {
    "@babel/cli": "7.7.7",
    "@babel/core": "7.7.7",
    "@babel/node": "7.7.7",
    "@babel/plugin-proposal-class-properties": "7.7.4",
    "@babel/plugin-proposal-decorators": "7.7.4",
    "@babel/plugin-proposal-do-expressions": "7.7.4",
    "@babel/plugin-proposal-export-default-from": "7.7.4",
    "@babel/plugin-proposal-export-namespace-from": "7.7.4",
    "@babel/plugin-proposal-function-bind": "7.7.4",
    "@babel/plugin-proposal-function-sent": "7.7.4",
    "@babel/plugin-proposal-json-strings": "7.7.4",
    "@babel/plugin-proposal-logical-assignment-operators": "7.7.4",
    "@babel/plugin-proposal-nullish-coalescing-operator": "7.7.4",
    "@babel/plugin-proposal-numeric-separator": "7.7.4",
    "@babel/plugin-proposal-optional-chaining": "7.7.4",
    "@babel/plugin-proposal-pipeline-operator": "7.7.4",
    "@babel/plugin-proposal-throw-expressions": "7.7.4",
    "@babel/plugin-syntax-dynamic-import": "7.7.4",
    "@babel/plugin-syntax-import-meta": "7.7.4",
    "@babel/polyfill": "7.7.0",
    "@babel/preset-env": "7.7.7",
    "@babel/preset-react": "7.7.4",
    "@essentials/request-timeout": "1.0.1",
    "@handsontable/react": "^4.0.0",
    "@hot-loader/react-dom": "16.8.6",
    "autoprefixer": "7.2.5",
    "babel-core": "^7.0.0-bridge.0",
    "babel-loader": "8.0.6",
    "babel-plugin-emotion": "9.1.2",
    "babel-plugin-react-generate-property": "^1.0.4",
    "body-parser": "1.18.2",
    "clean-webpack-plugin": "0.1.19",
    "connected-react-router": "6.5.2",
    "core-js": "3.1.4",
    "cross-env": "5.2.0",
    "css-loader": "0.28.7",
    "emotion": "9.2.12",
    "emotion-theming": "9.2.9",
    "es6-symbol": "3.1.1",
    "express": "4.16.2",
    "handsontable": "^8.1.0",
    "html-loader": "0.5.5",
    "html-webpack-plugin": "3.2.0",
    "loader-utils": "1.1.0",
    "lodash": "4.17.4",
    "mini-css-extract-plugin": "0.4.0",
    "moment": "2.19.1",
    "monaco-editor-webpack-plugin": "1.7.0",
    "postcss-loader": "2.0.10",
    "promise-polyfill": "^8.1.3",
    "prop-types": "15.6.0",
    "raw-loader": "^3.0.0",
    "react": "16.8.6",
    "react-dom": "16.8.6",
    "react-emotion": "9.2.12",
    "react-hot-loader": "4.8.8",
    "react-redux": "7.1.0",
    "react-router-dom": "5.1.2",
    "react-virtualized": "9.21.1",
    "redux": "3.7.2",
    "redux-saga": "1.0.1",
    "regenerator-runtime": "0.13.3",
    "style-loader": "0.20.1",
    "terser-webpack-plugin": "1.4.1",
    "url-loader": "0.6.2",
    "webpack": "4.42.0",
    "webpack-babel-env-deps": "^1.5.0",
    "webpack-cli": "3.3.11",
    "write-file-webpack-plugin": "4.5.0"
  },
  "devDependencies": {
    "babel-eslint": "10.1.0",
    "babel-jest": "^23.4.2",
    "eslint": "7.1.0",
    "eslint-config-prettier": "6.11.0",
    "eslint-plugin-prettier": "3.1.3",
    "husky": "0.14.3",
    "jest": "^23.6.0",
    "npm": "6.5.0",
    "prettier": "1.18.2",
    "pretty-quick": "1.4.1",
    "webpack-bundle-analyzer": "2.11.1",
    "webpack-dev-server": "3.10.3"
  }
```

**Comment by AMBudnik** [comment]
Hi @shawnxusy 

Thank you for the file. Would it be too much if I asked for the repository access? There are still some answers that repository access would solve.

**Comment by shawnxusy** [comment]
@AMBudnik I just found that our staging env seems to show up fine, so it might have something to do with local dev setup. I can dig deeper with that, thanks a lot for your time!
