### ISSUE TITLE
The trimWhitespace property does not work when pasting from .xlsx files

### ISSUE THREAD

**Issue by GithubOfWZS** [handsontable/react-handsontable#212]
### Description
When I copy rows from the .xlsx file to the handsontable, the leading and trailing spaces in the data are not removed, But if I click on a cell, the space will be removed. Even if I set the 'trimRows' and 'trimWhitespace' property values to true, the problem remains.

### Steps to reproduce
1. Write a string with leading or trailing spaces in a .xlsx file;
2. Copy this string and paste it in a cell of handsontable;
3. Click the cell to see if the spaces exist.

### Demo

no changes to the original demo,but this issue can be reproduced.
https://jsfiddle.net/handsoncode/c6rgz08x/

### Your environment
* React wrapper version: same as the demo
* Handsontable version: same as the demo
* Browser Name and version: Chrome 87.0.4280.88(64 bit)
* Operating System: Windows10

**Comment by AMBudnik** [comment]
Hi @GithubOfWZS 

This issue seems to be the same as this one https://github.com/handsontable/handsontable/issues/3930
If there is something important what we missed please share a comment to https://github.com/handsontable/handsontable/issues/3930
