### ISSUE TITLE
Redux example improvement

### ISSUE THREAD

**Issue by mattbretl** [handsontable/react-handsontable#23]
The [Redux example](http://codepen.io/handsoncode/pen/LWmvPX?editors=0010) breaks when onAfterChange fires with multiple objects in changes[] (e.g. when using the Drag Down feature).

Replacing the existing reduxStore.dispatch() with the following should fix it:
```
changes.forEach((change)=> {
  reduxStore.dispatch({
    id: reduxStore.getState().changes.length,
    type: 'change',
    row: change[0],
    column: change[1],
    oldValue: change[2],
    newValue: change[3]
  });
});
```

Better yet, only dispatch if the cell value truly changed:
```
changes.forEach((change)=> {
  if (change[2] !== change[3]) {
    reduxStore.dispatch({
      id: reduxStore.getState().changes.length,
      type: 'change',
      row: change[0],
      column: change[1],
      oldValue: change[2],
      newValue: change[3]
    });
  }
});
```

**Comment by jansiegel** [comment]
@mattbretl Is the current Redux example working fine, @mattbretl? I can't seem to find the breaking point in it now. 
https://docs.handsontable.com/5.0.0/frameworks-wrapper-for-react-examples-redux.html

**Comment by mattbretl** [comment]
Yes, this is fixed now. Thanks for following up.
