### ISSUE TITLE
Validators are broken

### ISSUE THREAD

**Issue by kschingiz** [handsontable/react-handsontable#24]
I created a HotTable, some columns have built-in validators, some have my custom validators.
When any of validators falls and calls callback function with false, cells are not red colored.
Example is here:
https://codepen.io/kschingiz/pen/QMxNEJ
As you can see in this example I used one validator for all columns, and it always falls on validation, but none of cells are red colored.
Now as a temp solution I call validateCells on onAfterRender event:

  ```
onAfterRender(isForced){
    Meteor.setTimeout(() => {
      this.table.hotInstance.validateCells();
    }, 100);
    }
```

But this gives me huge overhead, and table gets stuck on dataset of +10k cells.
Example here: 
https://codepen.io/kschingiz/pen/MvXyOg

How to solve this?

**Comment by Whythawye** [comment]
Handsontable does not automatically validate the table on initialization as mentioned here:

https://github.com/handsontable/handsontable/issues/4048

You need to tell it to call validateCells(), but you do not need to do it every single render, only on the first one. So just put it into componentDidMount of your wrapping component like so:

```componentDidMount () {
  this.refs.table.hotInstance.validateCells()
}```

You, of course, need to declare the `ref` for the table in your declaration, though, like so:

```...
ref={'table'}
...```

**Comment by AMBudnik** [comment]
Thank you for referring to my post @Whythawye

**Comment by Whythawye** [comment]
An important note on this, however, is illustrated in my edit of your example: 

https://codepen.io/anon/pen/yPMOBE

Every time you change the state, the table gets re-initialized. And when it gets re-initialized, it resets the htInvalid classes on all the cells, and doesn't re-trigger validateCells(). So this is still a big issue for performance, since you have to re-validate whenever you change state.

**Comment by kschingiz** [comment]
I am sorry for the late reply.
@Whythawye 
> So this is still a big issue for performance, since you have to re-validate whenever you change state.
yes I did so, everytime when state changes I revalidate all of cells, unfortunately we can't validate only changed column, because other columns reset their state.
I just debounced the validation when something is changed.
