### ISSUE TITLE
Cannot find css-loader

### ISSUE THREAD

**Issue by chetanmotamarri** [handsontable/react-handsontable#25]
I'm using browserify to bundle. Getting this error when tried to compile.

Error: Cannot find module '!!../../css-loader/index.js!./handsontable.full.css' from '/node_modules/react-handsontable/dist'

Anyone facing same kind of issue ?

**Comment by SyntaxChris** [comment]
Yes I am dealing with the same issue.  I don't see a css file anywhere in this package.

**Comment by AMBudnik** [comment]
Hi @chetanmotamarri @SyntaxChris have you managed to find an answer?

ps. the `handsontable.full.css` is the `node_modules` but in the `handsontable/dist`

**Comment by SyntaxChris** [comment]
@AMBudnik I just extracted the css file into my app as a work around. The rest of the assets work just fine.

**Comment by AMBudnik** [comment]
Thanks for a prompt reply.
