### ISSUE TITLE
Uncaught ReferenceError: __HOT_BUILD_DATE__ is not defined

### ISSUE THREAD

**Issue by ls176** [handsontable/react-handsontable#26]
When I was using electron development, I found this error:
> Uncaught ReferenceError: \_\_HOT_BUILD_DATE\_\_ is not defined

how can i fix this issue?

**Comment by kiwipxl** [comment]
I'm not entirely why, but upgrading to latest (at this time, 0.34.1) solved the issue for me.
Made a pull request here for the vue extension [here](https://github.com/handsontable/vue-handsontable-official/pull/10)
Try upgrading for react-handsontable and see if it works here as well. I'd make a pull request, but I don't have much time to test it.

**Comment by hyperd20002000** [comment]
Did you ever find ha fix for this. I'm finding a similar issue when I run Jest

**Comment by ls176** [comment]
Before require react-handsontable , I add the follow code
`
global.__HOT_BUILD_DATE__   = "";
global.__HOT_PACKAGE_NAME__ = "";
global.__HOT_VERSION__      = "";
global.__HOT_BASE_VERSION__ = "";
`

**Comment by AMBudnik** [comment]
Thanks for sharing the tip.

I assume that the issue can be closed as there are no additional questions.

**Comment by masato-io** [comment]
I'm getting the same error (Uncaught ReferenceError: __HOT_BUILD_DATE__ is not defined) as well for Jest testing and adding global.__HOT_BUILD_DATE__ = ""; before react-handsontable import statement did not resolve an error in my case. I'm using recent version 0.3.1 of react-handsontable. Did anyone has a solution for this?

**Comment by yurachumak** [comment]
the same issue

**Comment by blackpost38** [comment]
In my case, I got this error with jest. So, I added global to config of jest like below.

I don't know what are `__HOT_BUILD_DATE__` and other things. But testing works well.

```json
// package.json
"jest": {
    "globals": {
      "__HOT_BUILD_DATE__": "",
      "__HOT_PACKAGE_NAME__": "",
      "__HOT_VERSION__": "",
      "__HOT_BASE_VERSION__": ""
    }
},
```

**Comment by jhonner** [comment]
Still, same problem here, using basic-electron-react-boilerplate 0.7.0
( https://github.com/pbarbiero/basic-electron-react-boilerplate )
with handsontable 0.36.0 and react-handsontable 0.3.1

**Comment by ocrickard** [comment]
Still have the same problem here too.

**Comment by bbmerong** [comment]
Is there a solution for that, I cannot solve this problem, Please let me know how.

**Comment by davidmicksch** [comment]
I ran across the same problem with react-handsontable under electron and resolved it by inserting the following line in my index.html file before launching react.

  <script type="text/javascript">global.__HOT_BUILD_DATE__ = ""; global.__HOT_PACKAGE_NAME__ = ""; global.__HOT_VERSION__ = ""; global.__HOT_BASE_VERSION__ = "";</script>
