### ISSUE TITLE
How to get HotInstance and selectCell in react?

### ISSUE THREAD

**Issue by pmunin** [handsontable/react-handsontable#27]
I need to do operations with hotInstance - like selecting cell etc, which is not available through updating settings. How to do it with react-handsontable?

**Comment by AMBudnik** [comment]
Hi @pmunin 

please find the demo attached https://codepen.io/anon/pen/QgQmLX?editors=0010

**Comment by AMBudnik** [comment]
I assume that the issue is solved as there are no additional questions. However, feel free to leave a comment if needed.
