### ISSUE TITLE
what's the difference between react-handsontable and Handsontable(javascript) in terms of features

### ISSUE THREAD

**Issue by menes127** [handsontable/react-handsontable#29]
I though react-handsontable is an react wrapper for Handsontable entirely and it is supposed to cover all  the features Handsontable had. But I encounted an cell custom renderers issue below, the chrome throws an error below. It seems like react-handsontable only covers some of Handsontalbe features? May I know what's the difference between react-handsontable and Handsontable(javascript) in terms of features?

`uncaught at sagaWithCatch TypeError: Cannot read property 'NumericRenderer' of undefined
`
```
import HotTable from 'react-handsontable';
export function sumYieldRowRenderer(instance, td, row, col, prop, value, cellProperties) {
  td.style.fontWeight = 'bold';
  td.style.background = '#c0c0c0';
  cellProperties.type = 'numeric';
  cellProperties.format = '0.[00]%';
  cellProperties.readOnly = true;

  HotTable.renderers.NumericRenderer.apply(this, arguments);
}
```

**Comment by AMBudnik** [comment]
Hi @menes127 

Try to add

`import Handsontable from 'handsontable';`

and then use the renderer

`renderer={sumYieldRowRenderer}`

I have checked that on my production and it works.

**Comment by menes127** [comment]
@AMBudnik , Great, Thank you very much, it works. I really want to replace react-handsontable with handsontable(javascript) in my project. but the biggest problem is that I cannot find more docs and examples to how to use react-handsontable, even though in this case, I did not know I can import handsontable by `import Handsontable from 'handsontable';` 
so my questions is how to find more examples? and what can be done by handsontable(javascript) but cannot be done by react-handsontable. I am seriously evaluating the risk of react-handsontable replacement. thank you again.

**Comment by AMBudnik** [comment]
I am sure that we will be adding more examples soon. The developer who has made the wrapper is currently doing other tasks that will take him at least whole October.

In the meanwhile, I have one more demo that can help. Here https://codepen.io/anon/pen/QgQmLX?editors=0010 is an example on how to use the `updateSettings `method that will allow you to change nearly all settings in the table.

**Comment by menes127** [comment]
Hi @AMBudnik , Thanks for your demo but I have read it from README.md. 
What am I supposed to say, there is no different features between handsontable(javascript) and react-handonstable?

**Comment by AMBudnik** [comment]
The react-handsontable is only a wrapper. There shouldn't be any difference between the versions. Some of the features can be just harder to code, but I am not a React expert and did not test them all.

If the wrapper is updated to a certain version of Handsontable is should share all the fixes and features of the vanilla version.

**Comment by menes127** [comment]
@AMBudnik thanks for your clarification.
