### ISSUE TITLE
HotTable with webpack

### ISSUE THREAD

**Issue by masato-io** [handsontable/react-handsontable#3]
Hi, thank you for creating react compatible handsontable! Looks very promising and I would love to give it try. 

One question I had is how to deal with webpack with react-handsontable. I was able to fix original Handsontable webpack issue by implementing solution provided [here](https://github.com/handsontable/handsontable/issues/3718). However when I try to use HotTable, error says "handsontable is not defined" and I won't be able to display table.

Is there any way to fix this issue by any chance? Seems like react community is already set to use webpack as a default option going forward and not been able to work with it as an out-of-the-box support is little bit painful. I really would love to use handsontable with react webpack :) Your feedback would be really appreciated.

**Comment by jansiegel** [comment]
@masato-io, 
Currently, I'd suggest using the `expose-loader` in webpack to expose Handsontable and its dependencies to the global context. I know this solution isn't ideal, but it's a workaround.

Basically, in `webpack.config.js`, you'd have to set up your loaders like this:

```js
[
// other loaders...
  {
    test: require.resolve('handsontable'),
    loader: 'expose-loader?Handsontable'
  },
  {
    test: require.resolve('numbro'),
    loader: 'expose-loader?numbro'
  },
  {
    test: require.resolve('moment'),
    loader: 'expose-loader?moment'
  }, {
    test: require.resolve('pikaday'),
    loader: 'expose-loader?Pikaday'
  }, {
    test: require.resolve('zeroclipboard'),
    loader: 'expose-loader?ZeroClipboard'
  }
]
```

And then, in your `.jsx` file import all of them as follows:

```js
import moment from 'moment';
import numbro from 'numbro';
import pikaday from 'pikaday';
import Zeroclipboard from 'zeroclipboard';
import Handsontable from 'handsontable';
import HotTable from 'react-handsontable';
import 'handsontable/dist/handsontable.full.css';
```

(to import the `.css` file the `css-loader` might come in handy)

When we have something less invasive ready, we'll update `react-handsontable` to work with it as well.

**Comment by masato-io** [comment]
@jansiegel thank you for your response! Yes, your solution worked well and now I can see HotTable working!! excited to dive into react-handsontable adventure :)

**Comment by masato-io** [comment]
As my question is clearly answered, I'm closing out this ticket. Thanks.

**Comment by panesofglass** [comment]
Is this still necessary?

**Comment by AMBudnik** [comment]
Hi @panesofglass 
I'm not an expert but the wrapper hasn't been updated for a year so this tip may still be useful

**Comment by panesofglass** [comment]
I just tried it without, and it seems to no longer be required. The reason I asked is the [wiki](https://github.com/handsontable/react-handsontable/wiki/Installation-guide#using-webpack-and-babel) does not indicate the `expose-loader` is necessary.
