### ISSUE TITLE
How can I list dropdown values after getting result from api call

### ISSUE THREAD

**Issue by kamaldlk** [handsontable/react-handsontable#30]
1.while clicking dropdown filed should call api
2.after getting result need to list dropdown values
please provide me some examples both need to work dynamically.

**Comment by AMBudnik** [comment]
Have you tried the `afterChange `hook? It is basically called each time a dataset is changed and it provides a `source` parameter so you know what action triggered it in the first place.

**Comment by AMBudnik** [comment]
I think that we can close this issue as there are no additional questions/concerns
