### ISSUE TITLE
Handsontable's paste not working when in a Bootstrap Modal

### ISSUE THREAD

**Issue by ericlau-solid** [handsontable/react-handsontable#35]
The pasting of data from Excel to Handsontable is a key feature I must get working, yet while it works on normal react pages, it doesn't work inside a React Bootstrap Modal. Unfortunately I need this working inside an established modal so not using it is not a realistic option. This can be reproduced via a trivial use of Handsontable:

<HotTable data={[[1,2]]} />

I see an issue on this from handsontable: https://github.com/handsontable/handsontable/issues/1480

I am not sure though how to implement the workaround in React framework. Can this community provide some tips? Thanks.

**Comment by AMBudnik** [comment]
I think that we can close this issue as there are no additional questions/concerns
