### ISSUE TITLE
How to set a renderer such as an auto-complete renderer?

### ISSUE THREAD

**Issue by PhilAndrew** [handsontable/react-handsontable#36]
Previously in Javascript I would do the following but now I don't know how how to do it using this react-handsontable. There are build-in renderers such as DateRenderer I want to access.

Renderers are discussed here https://handsontable.com/blog/articles/getting-started-with-cell-renderers

Related stackoverflow https://stackoverflow.com/questions/44376971/custom-renderer-or-conditional-styling-in-handsontable

                           if (((row==2) || (row==3)) || (row==8)) {
                               HotTable.renderers.AutocompleteRenderer.apply(this, arguments);
                           } else if ((row>=4) && (row<=6)) {
                               HotTable.renderers.DateRenderer.apply(this, arguments);
                           } else
                               HotTable.renderers.TextRenderer.apply(this, arguments);
                       } else
                           HotTable.renderers.TextRenderer.apply(this, arguments);

**Comment by AMBudnik** [comment]
Hi @PhilAndrew 

Please take a look at the following topic https://forum.handsontable.com/t/how-to-set-a-custom-cell-renderer-with-handsontable-react/1600
(there's also an example)

**Comment by siefkenj** [comment]
I am having the same issue. The example linked to does not address how to get the `Handsontable` object which contains the `renderers`, since the react version of handsontable only exports the `HotTable` react object.

**Comment by nimesha95** [comment]
@wojciechczerniak  but i cannot pass the ref into the my HotTable instance
Here's what i'm using 

```
<HotTable ref="hot" settings={{
                        data: this.data,
                        columns: this.createColumnObjects(),
                        colHeaders: this.createColumnHeaders(),
                    }
                    } />
```

this is my _createColumnObjects_ function

```
createColumnObjects() {
        var columns = [
            {
                data: 'service',
                width: '120px',
                readOnly: true
            },
            {
                data: 'project',
                width: '120px',
                readOnly: true
            },
            {
                data: 'role',
                readOnly: true
            },
            {
                data: 'site',
                readOnly: true
            },
            {
                data: 'finalized',
                type: 'checkbox',
                className: 'htCenter',
                renderer: function( instance, td, row, col, prop, value, cellProperties ) {
                     this.refs.hot.hotInstance.renderers.CheckboxRenderer.apply( this, arguments );
                },
            }
        ]
        }
        return columns
    }
```

Any idea what i'm doing wrong?
