### ISSUE TITLE
Custom column headers

### ISSUE THREAD

**Issue by miachenmtl** [handsontable/react-handsontable#39]
We're thinking of migrating a project from Reactabular to HandsOnTable but running into problems with customizing column headers in a React-friendly way. 

What we'd like to do is have column headers that are editable when the user double-clicks the header cell, and then style the header cell with a different background color to indicate that it has been edited. Is there a (React-friendly) way to set the properties of the column headers the way one is able to set the properties of cells using the `cells` prop and passing in a function?

It would be ideal to be able to pass in React elements into the array that gets passed into `colHeaders`. I realize that it is possible to have custom HTML, but it would be an issue to create event handlers so that one could have a controlled text input like the ones described in [Facebook's docs](https://reactjs.org/docs/forms.html#controlled-components).

**Comment by AMBudnik** [comment]
Unfortunately, this option is unavailable. It has been reported as a feature request to the vanilla version https://github.com/handsontable/handsontable/issues/460
