### ISSUE TITLE
how to call method

### ISSUE THREAD

**Issue by masato-io** [handsontable/react-handsontable#4]
Hi, I was reading how to call method on here: http://docs.handsontable.com/0.16.1/Core.html and I was wondering what is the best way to call method on react-handsontable. Specifically, I'm currently trying to play around with getCell(row, col, topmost){Element} method. Your advice would be appreciated!

**Comment by exytab** [comment]
Hi, @masato-io, I don`t know about best way, but I use refs to call handsontable methods. 

Component:
`<HotTable root="hot" ref="hot" />`

Method:
`this.refs.hot.hotInstance.getCell(row, col, topmost)`

**Comment by masato-io** [comment]
hey @exytab, thank you for your reply. It worked great! Really appreciate your help 👍

**Comment by masato-io** [comment]
as my question is clearly answered by @exytab, I'm closing this ticket.

**Comment by masato-io** [comment]
reopening for follow-up question on this...I have code that looks something like below:

```
  test(){
    return this.refs.hot.hotInstance.getCellMetaAtRow(n)
  }

  render() {
    return (
      <div>
          <HotTable root="hot" ref="hot"
              afterChange: function (change, source) {
                  *** here want to call "test" function to get CellMeta value ***
              }
          }} />
      </div>
    );
  }
```

usually in order to use refs in react, I do something like <div onClick={this.test.bind(this)}> but I'm not sure how I can get returned value of test() within afterChange function so that I can do:
1. determine which cell was edited via using afterChange
2. determine what id is associated with that edited row via using getCellMetaAtRow
3. call update method via rest api I'm using to update cell value

Your advice would be appreciated.

**Comment by masato-io** [comment]
oh never mind...I just had to bind afterChange function. thanks!
