### ISSUE TITLE
Using Nested Rows Plugin

### ISSUE THREAD

**Issue by johnrhampton** [handsontable/react-handsontable#43]
Is there documentation on how to use the Nested Rows plugin within the React wrapper?  We are able to use this feature on the pure JS version of HOT, but not within the wrapper.  I feel like we are missing something obvious.

Any documentation or examples would be greatly appreciated.

Nested Rows Documentation:
https://docs.handsontable.com/pro/1.15.0/demo-nested-rows.html

**Comment by AMBudnik** [comment]
Hi @johnrhampton 

I guess that I have just replied on your email but for other people with the same question I can copy the answer.

You just need to add `nestedRows={true}` to the initialization settings and make sure that the `data `is nested. To get a working example I just took the data from this example  https://docs.handsontable.com/pro/1.15.0/demo-nested-rows.html
Also, you should remember to add `rowHeaders={true}` if you did not turn them on in the first place.

**Comment by johnrhampton** [comment]
Thanks @AMBudnik.  We thought it was going to be something simple.  I created a codepen to demonstrate this functionality.

https://codepen.io/johnrhampton/pen/wpjWLq
