### ISSUE TITLE
Formulas={true} does not work with HotTable component

### ISSUE THREAD

**Issue by jehunter5811** [handsontable/react-handsontable#44]
Every other setting I've tried from the plain JS implementation of Handsontable into React has worked except formulas. Examples: 

manualColumnResize={true}
minSpareRows="1"
contextMenu={true}

Those all work as expected. This doesn't: 

formulas={true}

Is this missing or am I missing a dependency somewhere that's not documented?

**Comment by AMBudnik** [comment]
Hi @jehunter5811 

it works fine on my local machine.

What do you get in the cell that should hold the formula?
Have you tried to use any other PRO feature?

**Comment by jehunter5811** [comment]
Hi @AMBudnik, 

That's the problem. Didn't realize originally that formulas are confined to PRO accounts only. I'll close the issue. 

Thanks!
