### ISSUE TITLE
Maintain "history" on `state` update

### ISSUE THREAD

**Issue by jamesckemp** [handsontable/react-handsontable#45]
I've noticed that anytime the `state` is updated, regardless of the property, the undo/redo history is lost. Is there a way to prevent this?

**Comment by AMBudnik** [comment]
Hi @jamesckemp 

what do you mean by `state`? Can you share any scenario that I can take to replicate the issue?

**Comment by jamesckemp** [comment]
Hey, take this for example:

https://codepen.io/jamesckemp/pen/PQQeVN?editors=0010

Every 2 seconds some new data is added to the table. If you update any data while this process is happening, as soon as more data is loaded in, the undo/redo abilities are lost.

If you wait until the end (31 rows) and then start modifying data, undo/redo works again.

Does that make sense?

**Comment by AMBudnik** [comment]
Thank you, now it's clear. I got the same result and you're right that it can be a problem. Especially when you build an app with multiple-user access. 

I have checked a similar scenario with Vanilla version at http://jsfiddle.net/8zj86Lrk/ but you've used `setTimeout` and I took `setInterval` which allowed me (as a user) to perform additional steps while the script is running on the background.

**Comment by jamesckemp** [comment]
Just to clarify - it doesn't matter what part of the `state` I update, it'll wipe the undo/redo history. Take this for example:

https://codepen.io/jamesckemp/pen/ZrrRPN?editors=0010

You can make changes and undo/redo them with no issues. But make some changes, then click the "Update State" button and all of the undo/redo history is lost.

The `state` in this example has nothing to do with the table data that is displayed.

**Comment by AMBudnik** [comment]
Hi @jamesckemp 

sorry for keeping you waiting. I have asked one of our developers to investigate this case.

Can you check this demo https://codepen.io/handsoncode/pen/bLMKpp?editors=0010
It has been updated to by the settings to block history erasement.

**Comment by jamesckemp** [comment]
Hey,

I'm afraid that made no difference. To further explain the issue I have added an undo button to the pen, and attached a gif of the undo working, then not working after updating the state (using the pen you just provided)

https://codepen.io/jamesckemp/pen/RQJgOZ?editors=0010

![undo](https://user-images.githubusercontent.com/1853915/36529756-2de979da-17b1-11e8-967d-f202e0e0ddeb.gif)

**Comment by AMBudnik** [comment]
I hope that these time we can fix it, but feel free to let me know if still, something is missing.

So the demo with `state` does work https://codepen.io/handsoncode/pen/gvKGbJ?editors=0010 but without the actualization, `undoRedo` works https://codepen.io/handsoncode/pen/gvKGbJ?editors=0010

and here https://codepen.io/handsoncode/pen/gvKGbJ?editors=0010 and https://codepen.io/handsoncode/pen/MQXrra?editors=0010 it looks like the `setState` is cleaning the `undo` history (the `doneAction` and `undoneActions` are empty)

**Comment by coljung** [comment]
I think a problem i see, as far as i understand, is that the moment you update state, it basically re renders the whole grid, so its losing everything it had, including its history.

**Comment by jamesckemp** [comment]
@coljung That's right!

@AMBudnik I'm not seeing a solution based on what you provided there - have I missed something?

**Comment by AMBudnik** [comment]
Yes, but there is no way (currently) to rerender only the changed cell. 
We are planning to change that but [the project](https://trello.com/c/m9KTygSV/80-rewrite-renderers-to-improve-performance-2152) may take a month or more and it is planned to start in March/April.
