### ISSUE TITLE
Handsontable cell type

### ISSUE THREAD

**Issue by Quotechnique** [handsontable/react-handsontable#46]
Hi everyone !

I need to use an Handsontable cell type but I'm not able to get the selected item.
Here you can have a sample script like the one I'm using https://codepen.io/Calcimicium/pen/KQQvwM?editors=0010

I don't know how I can get the instance of Handsontable used by the cell, like in the example gived on the website https://docs.handsontable.com/0.33.0/demo-handsontable.html

Does someone can help me ?

**Comment by AMBudnik** [comment]
It looks like you can only get the index when someone double-clicks it in this example. You can try using `afterSelectionEnd` hook https://codepen.io/anon/pen/GQQBZx?editors=0010

**Comment by Quotechnique** [comment]
In your example you've placed the `afterSelectionEnd` on the main Handsontable component.
What I need

**Comment by Quotechnique** [comment]
Thanks to you @AMBudnik I discovered it was not necessary to use `getValue` to change the value of my handsontable cell type. I think I don't need the `afterSelectionEnd` hook either.

The problem is, instead of setting another `Chapter` object for the edited row, it only changes the label of the current chapter, because of the `data: "chapter.label"` property I think.

As you can see in this example (https://codepen.io/Calcimicium/pen/rJJQBB?editors=0010), when you select another chapter, all occurences of it are changed in the whole table. I put a log in the `afterChange` hook to see what is changed.

**Comment by AMBudnik** [comment]
And that we call an improvement. Great idea @Quotechnique

**Comment by Quotechnique** [comment]
Oh ! So this is not possible for the moment ?

**Comment by Quotechnique** [comment]
OK ! New step passed !
Finally I think I will use `getValue` property.
The problem was I used the arrow functions syntaxe which does not redefine `this`, and that's why I couldn't use `getSelected()` and `getSourceDataAtRow()` functions.

    this.settings = {
      // ...
      columns   : [
        { data: "account.common", type: "checkbox" },
        {
          data: "chapter",
          handsontable: {
            autoColumnSize: true,
            colHeaders    : ["Number", "Label"],
            columns       : [
              { data: "number" },
              { data: "label" }
            ],
            data          : getChapters(),
            // Here you have to not use arrow function syntaxe
            // otherwise "this" is not redefined...
            getValue      : function() {
              const selection = this.getSelected()
              const data      = this.getSourceDataAtRow(selection[0][0])
              console.log({ data })
              return data
            }
          },
          type: "handsontable"
        },
        { data: "account.number" },
        { data: "account.label" }
      ],
      // ...
    }

https://codepen.io/Calcimicium/pen/GQxWLg?editors=0010

Now, the problem is `afterChange` is not triggered...

**Comment by AMBudnik** [comment]
Hi @Quotechnique 

I've asked our developer for help but as the progress is moving so fast I do not know if you've already made it work entirely.
If you wanted to get the `Chapter` + number here's one demo that may help https://codepen.io/handsoncode/pen/rJdKKo?editors=0010 or maybe better this one https://codepen.io/handsoncode/pen/VQXBvm?editors=0010
Let me know if I am getting the right path or just missed it.

**Comment by Quotechnique** [comment]
Hi @AMBudnik 

Unfortunately that is not the behavior I'm expecting.
I don't want the `Chapter` instance to be modified, I'd like to replace it by the one selected in the handsontable. That' why I'm returning the whole row data source instead of only the label.

**Comment by AMBudnik** [comment]
I am afraid that I haven't found any other way to make it work as expected

**Comment by AMBudnik** [comment]
I hope that you have found the perfect solution @Quotechnique 
I need to close the issue as there aren't any new comments since March
