### ISSUE TITLE
Update to handsontable 0.36.0

### ISSUE THREAD

**Issue by FlapKap** [handsontable/react-handsontable#48]
This might be me misunderstanding versioning, but is this package going to be updated to handsontable version 0.36.0?

**Comment by AMBudnik** [comment]
Hi @FlapKap 

You can choose the version of vanilla you want to work within your package.json file. The Handsontable uses the caret (`^`) range for updates so it should already be updated to `0.36.0`. A caret, in this case, would bump the version to anything less than `1.0.0`.

The wrapper version is something completely different is it usually does to relate to vanilla version (PRO or CE).

**Comment by FlapKap** [comment]
Hi @AMBudnik 

Thanks for your quick answer. However, after looking at the [caret semver documentation](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) it seems that this is only true if the major version is `1.0.0` or above. For `0.X ` it treats `X` as the major version. At least thats how I read it.

**Comment by jansiegel** [comment]
@FlapKap This wrapper has `handsontable` set as an external dependency, so it'll work with any Handsontable (CE) version you link with it. 
For example, the demo from `README.md` automatically gets the latest CE version from our docs, so currently it runs on `0.36.0`: https://codepen.io/handsoncode/pen/ygvaxv?editors=0010

The situation with the Pro version is a little bit more tricky, so you'd have to use our Wiki to guide you further.

**Comment by FlapKap** [comment]
@jansiegel I am working with this through npm and webpack by setting react-handsontable as a dependency. Since react-handsontable has `"handsontable": "^0.33.0"` as a dependency in its `package.json` and this is not compatible with version `0.36.0` doesn't this mean that when I build my project it will use version `0.33.0`?

**Comment by AMBudnik** [comment]
The wrapper has been updated to use `Handsontbale 4.0.0` just before the weekend so I believe that we can close this issue
