### ISSUE TITLE
Problem with handsontable not imported in src

### ISSUE THREAD

**Issue by baruinho** [handsontable/react-handsontable#5]
The way its implemented forces the project to use handsontable as a global variable or configuring a webpack alias.

I suggest to add handsontable as a peer dependency and import it on the source.

**Comment by jansiegel** [comment]
@baruinho Could you update your `react-handsontable` version to the latest release? We've changed the way it handles Handsontable. 
And by the way, thanks for the input, it's really appreciated, especially in such an early version.
