### ISSUE TITLE
Update certain cells without reloading the whole grid

### ISSUE THREAD

**Issue by coljung** [handsontable/react-handsontable#50]
Is this possible ?

I have a huge grid, and upon changing a cell, im calling an API to get some updates, these updates might affect a few cells.

Is there a way to update said cells, without having HotTable reloading the whole grid ?

**Comment by AMBudnik** [comment]
Hi @coljung 

Currently, it is not available to update only single cell/area of cells. The whole grid is rerendered when you change a single cell.

We are planning to change the behavior via, what I like to call an eco-rendering. But the project hasn't started yet. Here's a Trello card to follow for updates https://trello.com/c/m9KTygSV/80-rewrite-renderers-to-improve-performance-2152

**Comment by coljung** [comment]
Will this affect 'Undo' as well ?

When the whole grid is rerendered, does it keep the 'undo' history, or is that reseted as well ?

**Comment by AMBudnik** [comment]
The undo stack has (or should, as there are some issues related) hold the changes for all the cells regardless the rendering process.
