### ISSUE TITLE
Usage with handsontable-pro not working

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/react-handsontable#51]
This component works great by itself. I wanted to try out the pro features so I followed the wiki and installed `npm install handsontable-pro` and set a webpack alias:
```
resolve: {
  alias: {
    handsontable: path.resolve(__dirname, "node_modules", "handsontable-pro")
  }
}
```
I can see in my webpack bundle analyzer that `handsontable-pro` package is bundled in. However this is what it looks like when I turn on the pro feature `dropdownMenu` (along with `filters` and some other stuff):

![img](http://g.recordit.co/vF6ZdfPwhb.gif)

You can see that the regular features seem to work, but the `dropdownMenu` in the header is just an unstyled button that does nothing. Any idea what's going on?

**Comment by aaronbeall** [comment]
It seems that `react-handsontable` is still [loading `handsontable/dist/handsontable.full.css`](https://github.com/handsontable/react-handsontable/blob/master/src/react-handsontable.jsx#L4) even though I have an alias to `handsontable-pro`. I even tried an explicit alias of `handsontable/dist/handsontable.full.css` to `handsontable-pro/dist/handsontable.full.css` but I can see in the rendered page that the old CSS is loaded.

I added an explicit import of `handsontable-pro` CSS:
```
import "handsontable/dist/handsontable.full.css";
```
That kind of works, but some things look off. Basically now its loading *both* CSS files and they may be in conflict.

**Comment by AMBudnik** [comment]
Hi @aaronbeall 

thank you for sharing. I have a normal looking dropdown menu UI but the filter window does not open upon click. We definitely would have to check what's going on with the PRO and React wrapper

**Comment by JaysonCubicCompass** [comment]
any updates to this issue? Thanks

**Comment by AMBudnik** [comment]
The React and Vue wrappers will be updated later this year. We are planning to start the work on Q2/Q3

**Comment by jansiegel** [comment]
@aaronbeall We've just released a new version of the wrapper.

Could you switch to `@handsontable-pro/react` and test if it works fine now? I'm guessing it should, as you'll have to import the appropriate `css` files yourself.

Please refer to [docs.handsontable.com/react](//docs.handsontable.com/react) for more detailed installation instructions.

**Comment by aaronbeall** [comment]
@jansiegel Thanks for the update! I'm currently using a fork that has #63 but from the looks of the new wrapper I'm sure the style issues are solved. Cheers.
