### ISSUE TITLE
Add a custom editor

### ISSUE THREAD

**Issue by jamesckemp** [handsontable/react-handsontable#53]
How should I go about adding a custom editor when using the react wrapper? Attempting to integrate this: https://github.com/mydea/handsontable-chosen-editor

**Comment by AMBudnik** [comment]
Hi @jamesckemp 

It looks like a cool idea! unfortunately, I do not have any tutorials on how to create a custom editor in React wrapper. Have you tried to check the vanilla version tips at https://docs.handsontable.com/pro/1.17.0/tutorial-cell-editor.html?

**Comment by jamesckemp** [comment]
@AMBudnik I've checked it out, and got reasonably far with it. However, I was importing Handsontable in separately from the NPM repo and running the code with that. It got to a point where I think it was referencing a different instance of the plugin and couldn't access my cell data.

Is there a way to access `Handsontable.editors` from the react instance? I tried `this.refs.hot.hotInstance.editors` but it wasn't set.

**Comment by AMBudnik** [comment]
Hi @jamesckemp 

I have found an old demo with the following code

```
class CustomEditor extends Handsontable.editors.TextEditor {
    setValue(newValue) {
        this.TEXTAREA.value = !newValue ? 'DD/MM/YYYY' : newValue;
    }
    getValue() {
        return this.TEXTAREA.value.replace('DD/MM/YYYY', '');
    }
    focus() {
        super.focus();
        this.TEXTAREA.select();
    }
}

class App extends Component {
  render() {
    return (

      <div>
              <HotTable
                data={[
                [1,2,3],[4,5,6]
                    ]}
                colHeaders={true}
                rowHeaders={true}
                dropdownMenu={true}
                allowEmpty={false}
                renderer={sumYieldRowRenderer}
                validator={ipValidatorRegexp}
                editor={CustomEditor}
                nestedRows={true}
                formulas={true}
                contextMenu={true}
              />
      </div>

    );
  }
}
```


that seems to work

**Comment by totoSalad** [comment]
@AMBudnik  I am so sorry to find ur demo is not working for me. Could you provide a online demo to help me ?

**Comment by AMBudnik** [comment]
sure @totoSalad 

here's a small example that I have. It is pretty weird but it works so I guess that you'll find it helpful.

**Comment by totoSalad** [comment]
@AMBudnik  Thanks quite well!

**Comment by AMBudnik** [comment]
you're welcome :)
