### ISSUE TITLE
Efficiently updating data

### ISSUE THREAD

**Issue by aaronbeall** [handsontable/react-handsontable#54]
I am having some pretty bad performance issues and I think its related to the way I am changing data (integrating with my data model and sync with server). Boiled down I have something like this:

```
render() {
  const { projects, fields } = this.props;
  return (
    <HotTable data={ createTableData(projects)  } columns={ createColumns(fields) } />
  );
}
```
The `projects` and `fields` are arrays of objects from the server and stored in Redux. To convert it to table data the conversion functions look something like this:

```
function createTableData(projects) {
  return projects.map(projectToTableRow);
}
function projectToTableRow(project) {
  return project.values.reduce((row, value) => ({ ...row, [value.fieldId]: value.data }), {});
}
```
Here seems to be the problem: every time the `<HotTable>` is rendered, it creates new table `data` array (with all new objects) to pass to it. This causes a noticeable lag after making any small change to data.

Any time data is changed in the table I use `afterChange` to update the `projects` source data, which causes a re-render and again the table `data` array is rebuilt. So even a small cell change seems to cause a big performance hit (on a large data table like 300 rows 200 cols).

Looking at various Handsontable examples it seems the idea is to only create the `data` initially, and after that let the table own the data, syncing changes to an external data model. Is that right? In other words, if I replace `data` is it not efficiently redrawing *only what changed in the data* (as we normally do in React world)? If so, what is the expected route to keep data in sync with changes coming from outside the table? In some cases data is changed by server actions or other events and I need to sync it back to the table. Do I need to manually wire update `setDataAtCell` calls?

**Comment by AMBudnik** [comment]
It looks like the issue that we have discussed further at https://github.com/handsontable/handsontable/issues/3997

**Comment by aaronbeall** [comment]
@AMBudnik It's certainly related to large data (actually in some cases I have thousands of rows and hundreds of columns so these are rough numbers on the smaller side) but _this_ particular issue is not related to validation, just merely updating data programmatically with the React component. How should I do that? 

In the other issue you said work is being done to "rerender only changed cells so the validator will run only for those cells" -- are you saying that in this case calls to `hotInstance.updateSettings()` ([which is what the react-handsontable component does any time it is rendered](https://github.com/handsontable/react-handsontable/blob/master/src/react-handsontable.jsx#L80)) will only update cells whose values have changed? Because the entire data will have changed by reference, though not by value. This is the problem I'm wrestling with here.

What I've done at the moment is write my own React component wrapper which stores the data in state, and in `componentWillReceiveProps` I compare the previous data to the current data and only update if it differs. This way when Handsontable updates data going out it doesn't end up redrawing the whole table because the input data changes, but if the data is changed from the outside (from server) then it does redraw.

**Comment by AMBudnik** [comment]
We did not set any details about the methods, so we still do not know if the `updateSettings `will change its behavior or a new method will be added. I am not sure if passing so many breaking changes won't confuse our Customers.

Definitely, if you are using cell references and dependencies (like formulas) all related cells should recalculate. Also when you add metadata like 'make odd rows yellow-backgrounded' should refresh more than just one cell. It should run for all the odd rows in the table.

I can see that you have done a lot of work to make the project run smoothly. Can you send me an email at support[at]handsontable.com? I would love to keep you updated on our work.
