### ISSUE TITLE
How to get afterSetCellMeta called from custom contextMenu items

### ISSUE THREAD

**Issue by eskimoblood** [handsontable/react-handsontable#55]
I created my own items in the context menu:

```
textDecoration: {
            key: 'textDecoration',
            name: 'Text decoration',
            submenu: {
                items: [
                    {
                        key: 'textDecoration:1',
                        name: 'Bold',
                        callback: (key, options) =>
                            console.log(key, options) || 'bold',
                    },
                    { key: 'textDecoration:2', name: 'Italic' },
                ],
            },
        },
```
I assumed that the result of of the callback function would be end up in `afterSetCellMeta` call like the other clicks on the build in items in the context menu but nothing happens. Is there a way to make this work do I have to handle this by myself?

**Comment by AMBudnik** [comment]
Hi @eskimoblood 

Sorry, our React demo base is still basic. I have some examples of vanilla custom menus. Hope they'll help

http://jsfiddle.net/rdu2bq2z/ < `updateSettings` use in the `contextMenu`
https://jsfiddle.net/handsoncode/oypsodyu < `setCellMeta` way of adding metadata

**Comment by eskimoblood** [comment]
Thanks `setCellMeta` is what I'm looking for.

**Comment by AMBudnik** [comment]
Great! Glad I could help.
