### ISSUE TITLE
The afterMergeCells hook is not triggered

### ISSUE THREAD

**Issue by osinglee** [handsontable/react-handsontable#59]
I see handsontable has been updated, look at this timely update. Thanks

**Comment by AMBudnik** [comment]
Hi @osinglee 

is this still an issue? I've created a simple demo where this hook runs for both user and programmer merging http://jsfiddle.net/handsoncode/nysmhxjk/

**Comment by YE-Hao** [comment]
I’ve met the same problem, so how to solve it ? @osinglee

**Comment by AMBudnik** [comment]
Here's a React example with `afterMerceCells` https://codepen.io/anon/pen/aKBJGX?editors=0010 which seem to work fine. If your examples are more complicated and don't work let me know.

**Comment by YE-Hao** [comment]
thanks! it works @AMBudnik

**Comment by AMBudnik** [comment]
Great! Thanks for confirmation @YE-Hao 
I think that we can close this issue.
