### ISSUE TITLE
Cannot use full features of handsontable with the component

### ISSUE THREAD

**Issue by popo1221** [handsontable/react-handsontable#60]
I found that I cannot use the full features of handsontable. 
The component just references `handsontable.js`, but not `handsontable.full.js`. 
Is there any way to use the full features?

**Comment by AMBudnik** [comment]
Hi @popo1221 

all needed dependencies are downloaded each time you run `npm i` and are build to the end file. Do you get any errors or are not able to use some functionalities?

**Comment by popo1221** [comment]
Hi @AMBudnik 
My issue is as same as https://github.com/handsontable/react-handsontable/issues/51.

Thanks.

**Comment by AMBudnik** [comment]
Thank you for connecting the issues.
