### ISSUE TITLE
How to access and change selectColumns core method inside react-handsontable?

### ISSUE THREAD

**Issue by sagar-gavhane** [handsontable/react-handsontable#66]
I want to know that, how to access selectColumns menthod inside react-handsontable. I already tried to assign refs to hot table component ```<HotTable refs="hot"/>``` but still i cant access selectColumns method.

```
console.log(this.refs.hot.hotInstance.selectColumns);
```
// output - returns undefined

Thanks for reading this question.

**Comment by AMBudnik** [comment]
Hi @sagar-gavhane 

here's a working demo https://codepen.io/anon/pen/zjQadN?editors=0010
lines `71-73` define the instance refference

**Comment by sagar-gavhane** [comment]
Wow, Great example to access core methods.

Thanks a lot @AMBudnik

**Comment by dzmitrypanamarenka** [comment]
@Sagar Any other approaches? It's not so convenient if we include HotTable in other components and can't render it in such way.
If we speak about this rows from example

    const exampleComponent = ReactDOM.render(
    <ExampleComponent />, document.getElementById('example')
    );
    window.hotInstance = exampleComponent.refs.hot.hotInstance;

it's okay, when we render it as a separate component. But if I import it in App component and then render App component via ReactDom.render, I have no refs, just empty object
