### ISSUE TITLE
afterChange fired multiple times

### ISSUE THREAD

**Issue by masato-io** [handsontable/react-handsontable#7]
this might be related to this issue:
https://github.com/handsontable/handsontable/issues/3343

here is a demo with console:
![feb-11-2017 23-51-35](https://cloud.githubusercontent.com/assets/17076187/22860520/3bbe4f46-f0b5-11e6-88f8-a4293090dd1c.gif)

my code looks something like below:
```
export default class Home extends Component {

  constructor(){
    super();
    this.state = {
      contacts_table: [{}],
      display_columns: null,
      column_header: null
    }
  }

  componentDidMount() {
    request(options, function (error, response, body) {
      if (error) {
        console.log('error making request', error);
      } else if (response.statusCode >= 400) {
        console.log('HTTP error response', response.statusCode, body.message);
      } else {
        this.setState({contacts_table: body});
        // display_columns
        let first_row = this.state.contacts_table[0];
        let display_columns = []
        for(let i in first_row){
          display_columns.push({data: i})
        }
        this.setState({display_columns: display_columns})
        // column_header
        let column_header = []
        this.state.display_columns.map(i => column_header.push(i.data))
        this.setState({column_header: column_header})
      }
    }.bind(this));
  }

  render() {
    return (
      <div id="table">
          <HotTable root="hot" ref="hot" settings={{
              data: this.state.contacts_table,
              colHeaders: true,
              rowHeaders: true,
              minSpareRows: 1,
              dropdownMenu: true,
              stretchH: 'all',
              colHeaders: this.state.column_header,
              columns: this.state.display_columns,
              afterChange: function (change, source) {
                console.log(change);
                console.log(source);
              }.bind(this)
          }} />
      </div>
    );
  }

}
```

Is there any workaround to fire afterChange only once by any chance? Your advise would be appreciated!

**Comment by jansiegel** [comment]
@masato-io Thanks for noticing it, I really don't think that's how Handsontable should act in this situation. The problem is, `react-handsontable` is based on the `updateSettings` functionality, so this issue is quite severe.
I've added a *high* priority to the original issue ([handsontable#3343](https://github.com/handsontable/handsontable/issues/3343)). When it's resolved, I'll update `react-handsontable` as well.

**Comment by masato-io** [comment]
thanks for your reply @jansiegel. As I'm using paid API calls for backend, firing afterChange method multiple times without my intention is costly. Looking forward to it to be fixed! 👍

**Comment by masato-io** [comment]
confirmed v0.31.1 is working as expected now 👍
closing out this issue.
