### ISSUE TITLE
How do I update the dependencies handsontable

### ISSUE THREAD

**Issue by gavargas22** [handsontable/react-handsontable#73]
I want to change the dependency of handsontable 0.33.0 to handsontable 3.0.0. What is the best way of doing this?

**Comment by AMBudnik** [comment]
and here's the news https://github.com/handsontable/react-handsontable/pull/69 :) so please be patient. We should be able to update the wrapper tomorrow

**Comment by gavargas22** [comment]
Thank you!!

**Comment by dstdnk** [comment]
As long as awesome react-handsontable has not been updated - here is the trick (how I do it).
Go you your `node_modules` directory, find `react-handsontable` in there.
Open up `package.json`, find `dependencies.handsontable: "^0.33.0"` and change the version of `handsontable` to `"^3.0.0"`. 
While you're in `react-handsontable` - run `npm install handsontable`.
That's it!
Please be aware it's a temporary fix - we all are waiting for the official update!

**Comment by gavargas22** [comment]
thanks @dstdnk
