### ISSUE TITLE
is this wrapper for hands on table 4.0 or lower version of hands on table?

### ISSUE THREAD

**Issue by Subash48** [handsontable/react-handsontable#74]

**Comment by AMBudnik** [comment]
Hi @Subash48 

it should be updated to `4.0.0` till the end of next week

**Comment by Subash48** [comment]
But in NPM it shows Published a year ago

**Comment by AMBudnik** [comment]
Yes, last (current) version of the wrapper is set to `"handsontable": "^0.33.0"` but will be updated soon to `4.0.0`
