### ISSUE TITLE
Binding the React element to a Handsontable instance

### ISSUE THREAD

**Issue by ralvessa** [handsontable/react-handsontable#75]
With this new version 1.0.0, and since `Handsontable` is no longer part of the React wrapper and can't be accessed using a reference, how can we bind the React element to a `Handsontable` instance and invoke its API?

I tried the following approach, but it didn't work – it actually added a new table to the DOM:

```
const container = document.getElementById(...);
const settings = ...;

const hot = new Handsontable(container, settings);
```

**Comment by wojciechczerniak** [comment]
`HotTable` component has `hotInstance` property which is the instance that is already binded to the DOM. You can create a [reference](https://reactjs.org/docs/refs-and-the-dom.html) to `HotTable` component to access it's properties.

**Comment by ralvessa** [comment]
Thanks for your help! It might be worth adding this to the `README`.
