### ISSUE TITLE
Remove sourceMap from dist files

### ISSUE THREAD

**Issue by budnix** [handsontable/react-handsontable#8]
In the latest version of wrapper distribution files (`react-handsontable.js` and `react-handsontable.min.js`) contain sourceMap. It should be moved to the separate file (`*.map`) to make dist files more optimized.

Related documentation https://webpack.github.io/docs/configuration.html#devtool

**Comment by budnix** [comment]
After investigation I've found that this line https://github.com/handsontable/react-handsontable/blob/master/package.json#L59 generates dists for development use only (`-d` argument). After removing this argument webpack should bundle package using all options provided in `webpack.config.js` config file.

**Comment by jansiegel** [comment]
Should work fine after `0.2.1`.
