### ISSUE TITLE
Collapse function doesn't work with columnSorting

### ISSUE THREAD

**Issue by lightsound** [handsontable/react-handsontable#80]
I used collapse function with sorting, but it did not work.
So I made this example, try to uncomment  `columnSorting`.
https://stackblitz.com/edit/react-handsontable-test-collapse

**Comment by AMBudnik** [comment]
Hi @lightsound 

please track changes to the following issue https://github.com/handsontable/handsontable/issues/4999 it's the HAndsontable - not the wrapper's fault.

**Comment by lightsound** [comment]
@AMBudnik Thanks for your quick reply. 

I got it. I searched for past issues before posting issue, but it seems I didn't find it well. It is additional information, it doesn't work well `collapseSection` as well as `collapseAll`.

This issue seems like a fatal bug, so  I hope it will be fixed.

**Comment by AMBudnik** [comment]
HI @lightsound 

we just published beta which fixed related issue https://github.com/handsontable/handsontable/issues/4999

Below are the resources

```html
</style><script src="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.js"></script><link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/gh/handsontable/handsontable@release/8.0.0-beta.1/dist/handsontable.full.css">
```

And this is how you can download the beta from NPM

`npm i handsontable@beta`

**Comment by AMBudnik** [comment]
Hi @lightsound referenced issue is solved. Please update your Handsontable for React to `v4.0.0`.
