### ISSUE TITLE
How can I use the updateSettings() to change my table settings on React?

### ISSUE THREAD

**Issue by whyjay17** [handsontable/react-handsontable#82]
I am using a HandsonTable component in my component. 

During my application process, I render a HandsonTable on a certain step. On this step, I enable the merge option by assigning `[  'mergeCells' ]` on `contextMenu` attribute of the component. After user makes changes on the table, the user can go to the next step. The next step has the same table with the updated value since it's the same component. Now in this step, I want to disable the `mergeCells` option and add a `'row_above', 'row_below'` option. 

I thought I had to use the updateSettings function like:

```
        this.updateSettings({
          contextMenu: ['row_above', 'row_below', 'mergeCells'],
        })
```

But this one says `updateSettings` is not a function.

I really want to know how this can be used in React and a clear example of how settings can be changed dynamically.

Thanks in advance.

**Comment by AMBudnik** [comment]
Hi @whyjay17 

it looks like the `this` doesn't correspond to the instance of Handsontable. Please check this demo https://codepen.io/anon/pen/ZRwNXZ?editors=0010

At `73-75` I define an instance of Handsontable
At `78-80` I change the `contextMenu`

**Comment by whyjay17** [comment]
@AMBudnik 

Thanks for the great example. When I tried to incorporate into my code, it gives me a `Target container is not a DOM element.` error on the line `const exampleComponent = ReactDOM.render(<ExampleComponent />, document.getElementById('example'));`

I checked the `id` of my div, but the error appears.

**Comment by AMBudnik** [comment]
Is there anything else I can do? I've already posted a demo in React for the `updateSettings` above. (It changes the context menu option list).

**Comment by AMBudnik** [comment]
I believe that I can close the issue as there's more than a week without any additional questions.
