### ISSUE TITLE
Having a trouble using afterMergeCells trigger in React.

### ISSUE THREAD

**Issue by whyjay17** [handsontable/react-handsontable#83]
What I am trying to do is, whenever I merge cells, I want to preserve that merged cell data (which cells were merged) and use that when I re-render the table.
```
export default class HotTableContainer extends Component {
    constructor(props) {
        super(props);
    }

    shouldComponentUpdate(nextProps) {
        return this.props.tableSettings !== nextProps.tableSettings;
    }

    render() {
        let { tableSettings } = this.props;

        return (
            <div id="example-component">
                <HoTable ref={item => (this.hot = item)} root="HOT" settings={tableSettings} style={{ color: "#eee" }} />
            </div>
        );
    }
}
```

This is how I use the table in my component. 

When I use other triggers like `afterSetDataAtCell` and `afterSetCellMeta`, they work as I intended.

ex) 
```
    componentDidUpdate(prevProps, prevState) {

        if (this.props.tableSettings.data && this.props.tableSettings.data.length > 1) {
            let width = this.props.tableSettings.data[0].length;
            let height = this.props.tableSettings.data.length;
            this.hot.hotInstance.addHook("afterSetDataAtCell", () => {
                this.exportCellData(width, height);
            });
            this.hot.hotInstance.addHook("afterSetCellMeta", (row, col, key, value) => {
                this.exportCellMeta(row, col, key, value);
            });
            
        }
    }
```
However, when I do 
```
this.hot.hotInstance.addHook("afterMergeCells", () => {
             console.log('something')
});
```

This never gets triggered.

It would be great to know how to trigger this and how to save the merged cell information.

**Comment by AMBudnik** [comment]
Hi @whyjay17 

maybe the instance hasn't been defined correctly?

Here is a demo https://codepen.io/anon/pen/rKRoam?editors=0010 of Handsontable logging `Merged` string in the `afterMergeCells` hook.

**Comment by whyjay17** [comment]
@AMBudnik 

Thanks. But how come the `afterSetDataAtCell` and `afterSetCellMeta` works with the instance `this.hot.hotInstance`? All other hooks in the documentation work except for the `afterMergeCells`.

**Comment by AMBudnik** [comment]
Hm.. in the example above both hooks (`afterMergeCells` and `afterSetCellMeta`) use the same definition of the Instance
https://codepen.io/anon/pen/NzJepx?editors=0010

**Comment by whyjay17** [comment]
I import the package using `import HoTable from "react-handsontable";`. Do I have to import it differently, or maybe use a different version? @AMBudnik

**Comment by AMBudnik** [comment]
The merging hook has been added in the Handsontable v0.37.0 (PRO 1.17.0) https://docs.handsontable.com/pro/1.17.0/tutorial-release-notes.html so every version after this one should work. However, I do not know if we did not have any issues between the latest version (4.0.0 used in my demo) and 1.17.0.
The react version used in this demo is `react-handsontable@0.3.1`

**Comment by whyjay17** [comment]
@AMBudnik If other hooks are working with the instance `this.hot.hotInstance`, shouldn't `afterMegeCells` also work without an issue? Do you see any other possible reason for this not working?

**Comment by AMBudnik** [comment]
It is really hard to say seeing only parts of the code. If you could create a demo of your implementation it would be easier. As you see it works in the demo that I've created. Maybe you call it outside the scope?

**Comment by whyjay17** [comment]
@AMBudnik Ok, I will try to check the version first and then re-try. If I want to use the most recent version of handson table, do I just have to re-install it in my package and use the same import statement: import HoTable from "react-handsontable";?

**Comment by AMBudnik** [comment]
You can just run `npm i` inside the project as the newest wrapper version uses newest Handsontable version. Currently, it is `4.0.0`

**Comment by whyjay17** [comment]
It still doesn't work with the right version. I realized there is a similar issue on: https://github.com/handsontable/react-handsontable/issues/59

In the example that you provided: https://codepen.io/anon/pen/rKRoam?editors=0010
it uses 
```const exampleComponent = ReactDOM.render(<ExampleComponent />, document.getElementById('example'));

window.hotInstance = exampleComponent.refs.hot.hotInstance;
```
But my code doesn't use the `ReactDOM.render`. Does this have anything to do with how to use the `hotInstance`?

**Comment by AMBudnik** [comment]
Our React expert is on the vacation and is back on Monday. I will ask him to check the topic.

**Comment by jansiegel** [comment]
@whyjay17 The `afterMergeCells` hook was introduces with Handsontable `0.37.0`. If you're using an older version of the react wrapper, you might have an older version of Handsontable.

Have you tried updating to the latest version (of both the wrapper and Handsontable)?
To do this, you'll need to install it as:
```
npm install handsontable @handsontable/react
```
and import it accordingly:
```
import { HotTable } from '@handsontable/react';
```

For more installation instructions, see our documentation: https://docs.handsontable.com/4.0.0/frameworks-wrapper-for-react-installation.html
