### ISSUE TITLE
Numbro version

### ISSUE THREAD

**Issue by coljung** [handsontable/react-handsontable#84]
I noticed that while Handsontable 4.0.0 uses numbro 2.x, react-handsontable still uses numbro 1.11.0

I wonder if this might be causing an issue with the formatting of some numbers.

I tried upgrading my handsontable-pro version today ( 1.18 to 4.0.0 ) and since my number format has been off.

I saw a comment about it maybe being related to react-handsontable, so i also went and upgraded it to 1.0.0.

Same issue.

Btw, i have asked a similar question on the handsontable forum as well as on its own github page.

**Comment by AMBudnik** [comment]
Thank you for reporting I have just updated the corresponding issue report on the vanilla board https://github.com/handsontable/handsontable/issues/5237

**Comment by AMBudnik** [comment]
Also, I've just got a tip from our developer.

The `react-handsontable` is deprecated. To get a newest version you should use `@handsontable/react`

**Comment by AMBudnik** [comment]
The issue has been described and solved at https://github.com/handsontable/handsontable/issues/5237
