### ISSUE TITLE
Jest test fails due to missing module

### ISSUE THREAD

**Issue by ghost** [handsontable/react-handsontable#92]
### Description
I'm writing a test for a react component and i'm getting this error 
``` 
● Test suite failed to run

    Cannot find module 'handsontable/plugins/_base' from 'bindRowsWithHeaders.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (node_modules/handsontable-pro/commonjs/plugins/bindRowsWithHeaders/bindRowsWithHeaders.js:9:13)
```

### Steps to reproduce

1. create an app: 
`create-react-app sample-test && cd sample-test`
2.   run `npm install @handsontable-pro/react handsontable-pro`
3.  replace content of App.js 
```
import React from 'react';
import 'handsontable-pro/dist/handsontable.full.css';

import {HotTable} from '@handsontable-pro/react';

class App extends React.Component {
  constructor(props) {
    super(props);
    this.data = [
      ["", "Ford", "Volvo", "Toyota", "Honda"],
      ["2016", 10, 11, 12, 13],
      ["2017", 20, 11, 14, 13],
      ["2018", 30, 15, 12, 13]
    ];
  }

  render() {
    return (
      <div id="hot-app">
        <HotTable data={this.data} colHeaders={true} rowHeaders={true} width="600" height="300" stretchH="all" />
      </div>
    );
  }
}
export default App;
```

4. run `npm test`

### Your environment
* CreateReact App: 1.5.2
* Handsontable version: 5
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @jericbas 

it's a Handsontable PRO issue. Please refer to https://github.com/handsontable/handsontable-pro/issues/97

**Comment by kevinhaas** [comment]
Any update on this? The issue you linked to was closed with no solution.

**Comment by kevinhaas** [comment]
I was able to fix this by adding the following to my jest config:
`    "moduleNameMapper": {
      "^handsontable": "handsontable"
    }`

**Comment by AMBudnik** [comment]
Thank you for sharing @kevinhaas

**Comment by Fenixp** [comment]
I just ran across the same issue, all handsontable modules imported from handsontable-pro could not be resolved. Kevinhaas's solution ended up working. 

Beware that an app created via create-react-app won't accept "moduleNameMapper" parameter when running "react-scripts test", so you either need to eject or use jest dependency outside of default react app.

**Comment by wojciechczerniak** [comment]
It's no longer needed to configure the mapper. We have removed `moduleNameMapper` from Handsontable `v7`.
